#include <R.h>
#include <Rinternals.h>
#define printf Rprintf

/*
  Generated by Make DParser Version 1.31.4ab9d43046e5d22ffb365ec5f5184a7cfee09b30
  Available at https://github.com/jplevyak/dparser
*/

#line 7 "/home/matt/src/monolix2rx/src/mlxtranOp.g.d_parser.c"
#include "dparse.h"

D_Reduction d_reduction_0_mlxtranOp = {1, 0, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_1_mlxtranOp = {1, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_2_mlxtranOp = {2, 2, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_3_mlxtranOp = {1, 2, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_4_mlxtranOp = {1, 3, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_5_mlxtranOp = {3, 4, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_6_mlxtranOp = {3, 5, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_7_mlxtranOp = {1, 6, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_9_mlxtranOp = {3, 7, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_10_mlxtranOp = {1, 8, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_12_mlxtranOp = {3, 9, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_13_mlxtranOp = {1, 10, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_14_mlxtranOp = {1, 11, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_15_mlxtranOp = {2, 12, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_19_mlxtranOp = {1, 13, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_20_mlxtranOp = {0, 13, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_21_mlxtranOp = {1, 14, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_22_mlxtranOp = {0, 14, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_23_mlxtranOp = {1, 15, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_24_mlxtranOp = {0, 15, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_25_mlxtranOp = {1, 16, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_26_mlxtranOp = {0, 16, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_27_mlxtranOp = {2, 17, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_28_mlxtranOp = {1, 18, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_29_mlxtranOp = {0, 18, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_30_mlxtranOp = {1, 19, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_32_mlxtranOp = {1, 20, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_35_mlxtranOp = {1, 21, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_36_mlxtranOp = {1, 22, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_37_mlxtranOp = {1, 23, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_38_mlxtranOp = {1, 24, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_39_mlxtranOp = {1, 25, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_40_mlxtranOp = {2, 26, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_41_mlxtranOp = {0, 26, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_42_mlxtranOp = {1, 27, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_44_mlxtranOp = {2, 28, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_0_mlxtranOp = {29, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_1_mlxtranOp = {30, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_2_mlxtranOp = {31, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_3_mlxtranOp = {32, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_4_mlxtranOp = {33, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_5_mlxtranOp = {34, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_6_mlxtranOp = {35, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_7_mlxtranOp = {36, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_8_mlxtranOp = {37, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_9_mlxtranOp = {38, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_10_mlxtranOp = {39, 0, 0, 0, -1, 0, NULL};
D_Shift d_shift_11_mlxtranOp = {40, 0, 0, 0, -2, 0, NULL};
D_Shift d_shift_12_mlxtranOp = {41, 0, 0, 0, -3, 0, NULL};
D_Shift d_shift_13_mlxtranOp = {42, 0, 0, 0, -4, 0, NULL};
D_Shift d_shift_14_mlxtranOp = {43, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_15_mlxtranOp = {44, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_16_mlxtranOp = {45, 0, 0, 0, 0, 0, NULL};

D_Shift * d_accepts_diff_0_0_mlxtranOp[] = {0};
D_Shift ** d_accepts_diff_0_mlxtranOp[] = {
d_accepts_diff_0_0_mlxtranOp
};

unsigned char d_scanner_0_0_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_0_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_0_1_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_1_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_1_1_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_1_mlxtranOp[] = {&d_shift_13_mlxtranOp,NULL};

D_Shift * d_accepts_diff_6_0_mlxtranOp[] = {0};
D_Shift ** d_accepts_diff_6_mlxtranOp[] = {
d_accepts_diff_6_0_mlxtranOp
};

unsigned char d_scanner_6_0_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 
};

D_Shift * d_shift_6_1_mlxtranOp[] = {&d_shift_15_mlxtranOp,NULL};

D_Shift * d_accepts_diff_11_0_mlxtranOp[] = {0};
D_Shift ** d_accepts_diff_11_mlxtranOp[] = {
d_accepts_diff_11_0_mlxtranOp
};

unsigned char d_scanner_11_0_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 
};

D_Shift * d_shift_11_1_mlxtranOp[] = {&d_shift_0_mlxtranOp,NULL};

D_Shift * d_accepts_diff_13_0_mlxtranOp[] = {0};
D_Shift ** d_accepts_diff_13_mlxtranOp[] = {
d_accepts_diff_13_0_mlxtranOp
};

unsigned char d_scanner_13_0_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 
};

unsigned char d_scanner_13_1_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_13_1_mlxtranOp[] = {&d_shift_14_mlxtranOp,NULL};

D_Shift * d_accepts_diff_15_0_mlxtranOp[] = {0};
D_Shift ** d_accepts_diff_15_mlxtranOp[] = {
d_accepts_diff_15_0_mlxtranOp
};

unsigned char d_scanner_15_0_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

unsigned char d_scanner_15_0_1_mlxtranOp[SCANNER_BLOCK_SIZE] = {
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

D_Shift * d_shift_15_0_mlxtranOp[] = {&d_shift_16_mlxtranOp,NULL};

D_Shift * d_accepts_diff_24_0_mlxtranOp[] = {0};
D_Shift * d_accepts_diff_24_1_mlxtranOp[] = {&d_shift_3_mlxtranOp,0};
D_Shift * d_accepts_diff_24_2_mlxtranOp[] = {&d_shift_4_mlxtranOp,0};
D_Shift ** d_accepts_diff_24_mlxtranOp[] = {
d_accepts_diff_24_0_mlxtranOp,
d_accepts_diff_24_1_mlxtranOp,
d_accepts_diff_24_2_mlxtranOp
};

unsigned char d_scanner_24_0_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 4, 0, 5, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_24_0_1_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 
0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 8, 6, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_24_1_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
9, 9, 10, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
};

unsigned char d_scanner_24_1_1_mlxtranOp[SCANNER_BLOCK_SIZE] = {
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 11, 9, 9, 9, 
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
};

unsigned char d_scanner_24_1_2_mlxtranOp[SCANNER_BLOCK_SIZE] = {
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
};

unsigned char d_scanner_24_2_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
12, 12, 12, 12, 12, 12, 12, 13, 12, 12, 12, 12, 12, 12, 12, 12, 
12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
};

unsigned char d_scanner_24_2_1_mlxtranOp[SCANNER_BLOCK_SIZE] = {
12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 14, 12, 12, 12, 
12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
};

unsigned char d_scanner_24_2_2_mlxtranOp[SCANNER_BLOCK_SIZE] = {
12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
};

D_Shift * d_shift_24_3_mlxtranOp[] = {&d_shift_8_mlxtranOp,NULL};

D_Shift * d_shift_24_4_mlxtranOp[] = {&d_shift_9_mlxtranOp,NULL};

unsigned char d_scanner_24_5_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_24_5_1_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 6, 
0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_24_6_1_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 6, 
0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 15, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_24_7_1_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 6, 
0, 6, 6, 6, 6, 16, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_24_9_mlxtranOp[] = {&d_shift_7_mlxtranOp,NULL};

unsigned char d_scanner_24_10_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 
17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 
17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 
17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 
};

unsigned char d_scanner_24_10_1_mlxtranOp[SCANNER_BLOCK_SIZE] = {
17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 
17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 
17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 
17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 
};

D_Shift * d_shift_24_12_mlxtranOp[] = {&d_shift_6_mlxtranOp,NULL};

unsigned char d_scanner_24_13_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
};

unsigned char d_scanner_24_13_1_mlxtranOp[SCANNER_BLOCK_SIZE] = {
18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
};

unsigned char d_accepts_diff_24_14_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_24_14_1_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_24_14_mlxtranOp[] = {&d_shift_4_mlxtranOp,NULL};

unsigned char d_scanner_24_15_1_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 6, 
0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 19, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_24_18_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_24_18_1_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 
0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_24_18_mlxtranOp[] = {&d_shift_3_mlxtranOp,NULL};

D_Shift * d_accepts_diff_40_0_mlxtranOp[] = {0};
D_Shift * d_accepts_diff_40_1_mlxtranOp[] = {&d_shift_10_mlxtranOp,0};
D_Shift ** d_accepts_diff_40_mlxtranOp[] = {
d_accepts_diff_40_0_mlxtranOp,
d_accepts_diff_40_1_mlxtranOp
};

unsigned char d_scanner_40_0_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 
3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_40_1_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_40_2_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 
7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_40_2_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_40_2_1_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_40_2_1_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_40_2_mlxtranOp[] = {&d_shift_10_mlxtranOp,NULL};

unsigned char d_scanner_40_3_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_40_3_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_40_4_1_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_40_4_mlxtranOp[] = {&d_shift_11_mlxtranOp,NULL};

unsigned char d_scanner_40_5_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_40_7_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 0, 11, 0, 0, 
12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_40_8_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 0, 13, 0, 0, 
14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_40_10_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_40_11_mlxtranOp[] = {&d_shift_12_mlxtranOp,NULL};

unsigned char d_scanner_40_12_0_mlxtranOp[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 0, 0, 0, 0, 0, 0, 
};

SB_uint8 d_scanner_0_mlxtranOp[2] = {
{NULL, {d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_1_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{d_shift_0_1_mlxtranOp, {d_scanner_0_1_0_mlxtranOp, d_scanner_0_1_1_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}}
};

SB_trans_uint8 d_transition_0_mlxtranOp[2] = {
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}}
};

SB_uint8 d_scanner_6_mlxtranOp[2] = {
{NULL, {d_scanner_6_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{d_shift_6_1_mlxtranOp, {d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}}
};

SB_trans_uint8 d_transition_6_mlxtranOp[2] = {
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}}
};

SB_uint8 d_scanner_11_mlxtranOp[2] = {
{NULL, {d_scanner_11_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{d_shift_11_1_mlxtranOp, {d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}}
};

SB_trans_uint8 d_transition_11_mlxtranOp[2] = {
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}}
};

SB_uint8 d_scanner_13_mlxtranOp[3] = {
{NULL, {d_scanner_13_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{d_shift_13_1_mlxtranOp, {d_scanner_13_1_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{d_shift_6_1_mlxtranOp, {d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}}
};

SB_trans_uint8 d_transition_13_mlxtranOp[3] = {
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}}
};

SB_uint8 d_scanner_15_mlxtranOp[2] = {
{d_shift_15_0_mlxtranOp, {d_scanner_15_0_0_mlxtranOp, d_scanner_15_0_1_mlxtranOp
 , d_scanner_15_0_1_mlxtranOp, d_scanner_15_0_1_mlxtranOp}},
{d_shift_15_0_mlxtranOp, {d_scanner_15_0_0_mlxtranOp, d_scanner_15_0_1_mlxtranOp
 , d_scanner_15_0_1_mlxtranOp, d_scanner_15_0_1_mlxtranOp}}
};

SB_trans_uint8 d_transition_15_mlxtranOp[2] = {
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}}
};

SB_uint8 d_scanner_24_mlxtranOp[19] = {
{NULL, {d_scanner_24_0_0_mlxtranOp, d_scanner_24_0_1_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{NULL, {d_scanner_24_1_0_mlxtranOp, d_scanner_24_1_1_mlxtranOp
 , d_scanner_24_1_2_mlxtranOp, d_scanner_24_1_2_mlxtranOp}},
{NULL, {d_scanner_24_2_0_mlxtranOp, d_scanner_24_2_1_mlxtranOp
 , d_scanner_24_2_2_mlxtranOp, d_scanner_24_2_2_mlxtranOp}},
{d_shift_24_3_mlxtranOp, {d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{d_shift_24_4_mlxtranOp, {d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{d_shift_0_1_mlxtranOp, {d_scanner_24_5_0_mlxtranOp, d_scanner_24_5_1_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{d_shift_0_1_mlxtranOp, {d_scanner_24_5_0_mlxtranOp, d_scanner_24_6_1_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{d_shift_0_1_mlxtranOp, {d_scanner_24_5_0_mlxtranOp, d_scanner_24_7_1_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{NULL, {d_scanner_24_1_0_mlxtranOp, d_scanner_24_1_1_mlxtranOp
 , d_scanner_24_1_2_mlxtranOp, d_scanner_24_1_2_mlxtranOp}},
{d_shift_24_9_mlxtranOp, {d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{NULL, {d_scanner_24_10_0_mlxtranOp, d_scanner_24_10_1_mlxtranOp
 , d_scanner_24_10_1_mlxtranOp, d_scanner_24_10_1_mlxtranOp}},
{NULL, {d_scanner_24_2_0_mlxtranOp, d_scanner_24_2_1_mlxtranOp
 , d_scanner_24_2_2_mlxtranOp, d_scanner_24_2_2_mlxtranOp}},
{d_shift_24_12_mlxtranOp, {d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{NULL, {d_scanner_24_13_0_mlxtranOp, d_scanner_24_13_1_mlxtranOp
 , d_scanner_24_13_1_mlxtranOp, d_scanner_24_13_1_mlxtranOp}},
{d_shift_24_14_mlxtranOp, {d_scanner_24_5_0_mlxtranOp, d_scanner_24_5_1_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{d_shift_0_1_mlxtranOp, {d_scanner_24_5_0_mlxtranOp, d_scanner_24_15_1_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{NULL, {d_scanner_24_1_0_mlxtranOp, d_scanner_24_1_1_mlxtranOp
 , d_scanner_24_1_2_mlxtranOp, d_scanner_24_1_2_mlxtranOp}},
{NULL, {d_scanner_24_2_0_mlxtranOp, d_scanner_24_2_1_mlxtranOp
 , d_scanner_24_2_2_mlxtranOp, d_scanner_24_2_2_mlxtranOp}},
{d_shift_24_18_mlxtranOp, {d_scanner_24_5_0_mlxtranOp, d_scanner_24_5_1_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}}
};

SB_trans_uint8 d_transition_24_mlxtranOp[19] = {
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_24_14_0_mlxtranOp, d_accepts_diff_24_14_1_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_24_18_0_mlxtranOp, d_accepts_diff_24_18_1_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}}
};

SB_uint8 d_scanner_40_mlxtranOp[14] = {
{NULL, {d_scanner_40_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{NULL, {d_scanner_40_1_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{d_shift_40_2_mlxtranOp, {d_scanner_40_2_0_mlxtranOp, d_scanner_40_2_1_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{d_shift_40_2_mlxtranOp, {d_scanner_40_3_0_mlxtranOp, d_scanner_40_2_1_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{d_shift_40_4_mlxtranOp, {d_scanner_40_1_0_mlxtranOp, d_scanner_40_4_1_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{d_shift_40_4_mlxtranOp, {d_scanner_40_5_0_mlxtranOp, d_scanner_40_4_1_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{NULL, {d_scanner_40_2_0_mlxtranOp, d_scanner_40_2_1_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{NULL, {d_scanner_40_7_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{NULL, {d_scanner_40_8_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{d_shift_40_4_mlxtranOp, {d_scanner_40_5_0_mlxtranOp, d_scanner_40_4_1_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{NULL, {d_scanner_40_10_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{d_shift_40_11_mlxtranOp, {d_scanner_40_10_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{NULL, {d_scanner_40_12_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}},
{d_shift_40_4_mlxtranOp, {d_scanner_40_12_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp
 , d_scanner_0_0_0_mlxtranOp, d_scanner_0_0_0_mlxtranOp}}
};

SB_trans_uint8 d_transition_40_mlxtranOp[14] = {
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_40_2_0_mlxtranOp, d_accepts_diff_40_2_1_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_40_3_0_mlxtranOp, d_accepts_diff_40_2_1_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}},
{{d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp
 , d_accepts_diff_0_0_0_mlxtranOp, d_accepts_diff_0_0_0_mlxtranOp}}
};

unsigned char d_goto_valid_0_mlxtranOp[] = {
0xbe,0x12,0x0,0x1,0x0,0x4};
unsigned char d_goto_valid_1_mlxtranOp[] = {
0x0,0x0,0x0,0x6,0x0,0x0};
D_Reduction * d_reductions_1_mlxtranOp[] = {&d_reduction_41_mlxtranOp};
D_RightEpsilonHint d_right_epsilon_hints_1_mlxtranOp[] = {{0, 13, &d_reduction_39_mlxtranOp}};
D_Reduction * d_reductions_2_mlxtranOp[] = {&d_reduction_38_mlxtranOp};
unsigned char d_goto_valid_4_mlxtranOp[] = {
0xb8,0x12,0x0,0x1,0x0,0x4};
D_Reduction * d_reductions_4_mlxtranOp[] = {&d_reduction_1_mlxtranOp};
D_Reduction * d_reductions_5_mlxtranOp[] = {&d_reduction_3_mlxtranOp};
unsigned char d_goto_valid_6_mlxtranOp[] = {
0x0,0x0,0x1,0x10,0x0,0x10};
D_Reduction * d_reductions_6_mlxtranOp[] = {&d_reduction_26_mlxtranOp};
D_RightEpsilonHint d_right_epsilon_hints_6_mlxtranOp[] = {{0, 16, &d_reduction_15_mlxtranOp}};
unsigned char d_goto_valid_7_mlxtranOp[] = {
0x0,0x80,0x0,0x10,0x0,0x10};
D_Reduction * d_reductions_7_mlxtranOp[] = {&d_reduction_24_mlxtranOp};
D_RightEpsilonHint d_right_epsilon_hints_7_mlxtranOp[] = {{0, 18, &d_reduction_15_mlxtranOp}};
unsigned char d_goto_valid_8_mlxtranOp[] = {
0x0,0x40,0x0,0x10,0x0,0x10};
D_Reduction * d_reductions_8_mlxtranOp[] = {&d_reduction_22_mlxtranOp};
D_RightEpsilonHint d_right_epsilon_hints_8_mlxtranOp[] = {{0, 20, &d_reduction_15_mlxtranOp}};
unsigned char d_goto_valid_9_mlxtranOp[] = {
0x0,0x20,0x0,0x10,0x0,0x10};
D_Reduction * d_reductions_9_mlxtranOp[] = {&d_reduction_20_mlxtranOp};
D_RightEpsilonHint d_right_epsilon_hints_9_mlxtranOp[] = {{0, 22, &d_reduction_15_mlxtranOp}};
D_Reduction * d_reductions_10_mlxtranOp[] = {&d_reduction_4_mlxtranOp};
unsigned char d_goto_valid_11_mlxtranOp[] = {
0x0,0x0,0x0,0x20,0x0,0x0};
unsigned char d_goto_valid_13_mlxtranOp[] = {
0x0,0x0,0x0,0x18,0x0,0x18};
D_Reduction * d_reductions_13_mlxtranOp[] = {&d_reduction_39_mlxtranOp};
D_Reduction * d_reductions_14_mlxtranOp[] = {&d_reduction_2_mlxtranOp};
unsigned char d_goto_valid_15_mlxtranOp[] = {
0x0,0x0,0x0,0x0,0x0,0x20};
D_Reduction * d_reductions_16_mlxtranOp[] = {&d_reduction_15_mlxtranOp};
D_Reduction * d_reductions_17_mlxtranOp[] = {&d_reduction_25_mlxtranOp};
D_Reduction * d_reductions_18_mlxtranOp[] = {&d_reduction_15_mlxtranOp};
D_Reduction * d_reductions_19_mlxtranOp[] = {&d_reduction_23_mlxtranOp};
D_Reduction * d_reductions_20_mlxtranOp[] = {&d_reduction_15_mlxtranOp};
D_Reduction * d_reductions_21_mlxtranOp[] = {&d_reduction_21_mlxtranOp};
D_Reduction * d_reductions_22_mlxtranOp[] = {&d_reduction_15_mlxtranOp};
D_Reduction * d_reductions_23_mlxtranOp[] = {&d_reduction_19_mlxtranOp};
unsigned char d_goto_valid_24_mlxtranOp[] = {
0x40,0xd,0xe,0x1,0x7b,0x4};
D_Reduction * d_reductions_24_mlxtranOp[] = {&d_reduction_29_mlxtranOp};
D_Reduction * d_reductions_25_mlxtranOp[] = {&d_reduction_42_mlxtranOp};
D_Reduction * d_reductions_26_mlxtranOp[] = {&d_reduction_40_mlxtranOp};
D_Reduction * d_reductions_27_mlxtranOp[] = {&d_reduction_42_mlxtranOp};
D_Reduction * d_reductions_28_mlxtranOp[] = {&d_reduction_44_mlxtranOp};
D_Reduction * d_reductions_29_mlxtranOp[] = {&d_reduction_10_mlxtranOp};
D_Reduction * d_reductions_30_mlxtranOp[] = {&d_reduction_10_mlxtranOp};
D_Reduction * d_reductions_31_mlxtranOp[] = {&d_reduction_13_mlxtranOp};
D_Reduction * d_reductions_32_mlxtranOp[] = {&d_reduction_14_mlxtranOp};
D_Reduction * d_reductions_33_mlxtranOp[] = {&d_reduction_30_mlxtranOp};
D_Reduction * d_reductions_34_mlxtranOp[] = {&d_reduction_30_mlxtranOp};
D_Reduction * d_reductions_35_mlxtranOp[] = {&d_reduction_6_mlxtranOp};
D_Reduction * d_reductions_36_mlxtranOp[] = {&d_reduction_9_mlxtranOp};
D_Reduction * d_reductions_37_mlxtranOp[] = {&d_reduction_7_mlxtranOp};
D_Reduction * d_reductions_38_mlxtranOp[] = {&d_reduction_7_mlxtranOp};
D_Reduction * d_reductions_39_mlxtranOp[] = {&d_reduction_12_mlxtranOp};
unsigned char d_goto_valid_40_mlxtranOp[] = {
0x0,0x0,0xf0,0x0,0x80,0x3};
D_Reduction * d_reductions_41_mlxtranOp[] = {&d_reduction_28_mlxtranOp};
D_Reduction * d_reductions_42_mlxtranOp[] = {&d_reduction_5_mlxtranOp};
D_Reduction * d_reductions_43_mlxtranOp[] = {&d_reduction_35_mlxtranOp};
D_Reduction * d_reductions_44_mlxtranOp[] = {&d_reduction_36_mlxtranOp};
D_Reduction * d_reductions_45_mlxtranOp[] = {&d_reduction_37_mlxtranOp};
D_Reduction * d_reductions_46_mlxtranOp[] = {&d_reduction_27_mlxtranOp};
D_Reduction * d_reductions_47_mlxtranOp[] = {&d_reduction_32_mlxtranOp};
D_Reduction * d_reductions_48_mlxtranOp[] = {&d_reduction_32_mlxtranOp};
D_Reduction * d_reductions_49_mlxtranOp[] = {&d_reduction_32_mlxtranOp};
unsigned short d_gotos_mlxtranOp[85] = {
4,5,6,7,8,23,9,17,10,13,14,11,15,7,8,19,
9,21,10,18,24,11,25,12,29,0,27,28,20,0,0,22,
0,12,0,16,16,47,48,49,50,3,26,16,16,0,0,16,
36,0,37,3,38,39,0,0,44,45,46,40,41,42,0,0,
0,0,43,0,0,0,0,0,0,0,30,31,0,32,33,34,
35,0,0,0,3};


D_State d_states_mlxtranOp[] = {
{d_goto_valid_0_mlxtranOp, 1, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_0_mlxtranOp, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_mlxtranOp, d_accepts_diff_0_mlxtranOp, -1},
{d_goto_valid_1_mlxtranOp, 16, {1, d_reductions_1_mlxtranOp}, {1, d_right_epsilon_hints_1_mlxtranOp}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_2_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {0, NULL}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 1, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_4_mlxtranOp, -9, {1, d_reductions_4_mlxtranOp}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_0_mlxtranOp, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_mlxtranOp, d_accepts_diff_0_mlxtranOp, -1},
{NULL, -2147483647, {1, d_reductions_5_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_6_mlxtranOp, 9, {1, d_reductions_6_mlxtranOp}, {1, d_right_epsilon_hints_6_mlxtranOp}, {0, NULL}, 1, NULL, (void*)d_scanner_6_mlxtranOp, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_6_mlxtranOp, d_accepts_diff_6_mlxtranOp, -1},
{d_goto_valid_7_mlxtranOp, 0, {1, d_reductions_7_mlxtranOp}, {1, d_right_epsilon_hints_7_mlxtranOp}, {0, NULL}, 1, NULL, (void*)d_scanner_6_mlxtranOp, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_6_mlxtranOp, d_accepts_diff_6_mlxtranOp, -1},
{d_goto_valid_8_mlxtranOp, -3, {1, d_reductions_8_mlxtranOp}, {1, d_right_epsilon_hints_8_mlxtranOp}, {0, NULL}, 1, NULL, (void*)d_scanner_6_mlxtranOp, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_6_mlxtranOp, d_accepts_diff_6_mlxtranOp, -1},
{d_goto_valid_9_mlxtranOp, 8, {1, d_reductions_9_mlxtranOp}, {1, d_right_epsilon_hints_9_mlxtranOp}, {0, NULL}, 1, NULL, (void*)d_scanner_6_mlxtranOp, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_6_mlxtranOp, d_accepts_diff_6_mlxtranOp, -1},
{NULL, -2147483647, {1, d_reductions_10_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_11_mlxtranOp, 7, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_11_mlxtranOp, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_11_mlxtranOp, d_accepts_diff_11_mlxtranOp, -1},
{NULL, -2147483647, {0, NULL}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 1, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_13_mlxtranOp, 1, {1, d_reductions_13_mlxtranOp}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_13_mlxtranOp, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_13_mlxtranOp, d_accepts_diff_13_mlxtranOp, -1},
{NULL, -2147483647, {1, d_reductions_14_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_15_mlxtranOp, 21, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_15_mlxtranOp, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_15_mlxtranOp, d_accepts_diff_15_mlxtranOp, -1},
{NULL, -2147483647, {1, d_reductions_16_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_17_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_18_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_19_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_20_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_21_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_22_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_23_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_24_mlxtranOp, -42, {1, d_reductions_24_mlxtranOp}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_24_mlxtranOp, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_24_mlxtranOp, d_accepts_diff_24_mlxtranOp, -1},
{NULL, -2147483647, {1, d_reductions_25_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_26_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_27_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_28_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_29_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_30_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_31_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_32_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_33_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_34_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_35_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_36_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_37_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_38_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_39_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_40_mlxtranOp, -17, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_40_mlxtranOp, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_40_mlxtranOp, d_accepts_diff_40_mlxtranOp, -1},
{NULL, -2147483647, {1, d_reductions_41_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_42_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_43_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_44_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_45_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_46_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_47_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_48_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_49_mlxtranOp}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1}
};

D_Symbol d_symbols_mlxtranOp[] = {
{D_SYMBOL_EBNF, "0 Start", 7, -1},
{D_SYMBOL_NTERM, "statement_list", 14, -1},
{D_SYMBOL_INTERNAL, "statement_list__3", 17, -1},
{D_SYMBOL_EBNF, "statement_list__2", 17, -1},
{D_SYMBOL_NTERM, "charOp1", 7, -1},
{D_SYMBOL_NTERM, "charOp2", 7, -1},
{D_SYMBOL_EBNF, "charOp2__6", 10, -1},
{D_SYMBOL_NTERM, "logicalOp", 9, -1},
{D_SYMBOL_EBNF, "logicalOp__8", 12, -1},
{D_SYMBOL_NTERM, "numOp", 5, -1},
{D_SYMBOL_NTERM, "char_t1", 7, -1},
{D_SYMBOL_NTERM, "char_t2", 7, -1},
{D_SYMBOL_NTERM, "statement", 9, -1},
{D_SYMBOL_INTERNAL, "statement__16", 13, -1},
{D_SYMBOL_INTERNAL, "statement__15", 13, -1},
{D_SYMBOL_INTERNAL, "statement__14", 13, -1},
{D_SYMBOL_INTERNAL, "statement__13", 13, -1},
{D_SYMBOL_NTERM, "number", 6, -1},
{D_SYMBOL_INTERNAL, "number__19", 10, -1},
{D_SYMBOL_EBNF, "number__18", 10, -1},
{D_SYMBOL_NTERM, "constant", 8, -1},
{D_SYMBOL_NTERM, "decimalint", 10, -1},
{D_SYMBOL_NTERM, "float1", 6, -1},
{D_SYMBOL_NTERM, "float2", 6, -1},
{D_SYMBOL_NTERM, "identifier", 10, -1},
{D_SYMBOL_NTERM, "whitespace", 10, 1},
{D_SYMBOL_INTERNAL, "whitespace__27", 14, -1},
{D_SYMBOL_EBNF, "whitespace__26", 14, -1},
{D_SYMBOL_NTERM, "singleLineComment", 17, -1},
{D_SYMBOL_STRING, "=", 1, -1},
{D_SYMBOL_STRING, "=", 1, -1},
{D_SYMBOL_STRING, "=", 1, -1},
{D_SYMBOL_STRING, "yes", 3, -1},
{D_SYMBOL_STRING, "no", 2, -1},
{D_SYMBOL_STRING, "=", 1, -1},
{D_SYMBOL_REGEX, "\\\\'([^\\\\'\\\\\\\\]|\\\\\\\\[^])*\\\\'", 41, -1},
{D_SYMBOL_REGEX, "\\\"([^\\\"\\\\\\\\]|\\\\\\\\[^])*\\\"", 38, -1},
{D_SYMBOL_STRING, "+", 1, -1},
{D_SYMBOL_STRING, "-", 1, -1},
{D_SYMBOL_REGEX, "0|([1-9][0-9]*)", 15, -1},
{D_SYMBOL_REGEX, "([0-9]+.[0-9]*|[0-9]*.[0-9]+)([eE][\\\\-\\\\+]?[0-9]+)?", 55, -1},
{D_SYMBOL_REGEX, "[0-9]+[eE][\\\\-\\\\+]?[0-9]+", 29, -1},
{D_SYMBOL_REGEX, "[a-zA-Z][a-zA-Z0-9_]*", 21, -1},
{D_SYMBOL_REGEX, "[ \\t\\r\\n]+", 13, -1},
{D_SYMBOL_REGEX, "[;]", 3, -1},
{D_SYMBOL_REGEX, "[^\\n]*", 7, -1},
};

D_ParserTables parser_tables_mlxtranOp = {
50, d_states_mlxtranOp, d_gotos_mlxtranOp, 1, 46, d_symbols_mlxtranOp, NULL, 0, NULL, 0};
