#include <R.h>
#include <Rinternals.h>
#define printf Rprintf

/*
  Generated by Make DParser Version 1.31.4ab9d43046e5d22ffb365ec5f5184a7cfee09b30
  Available at https://github.com/jplevyak/dparser
*/

#line 7 "/home/matt/src/monolix2rx/src/mlxtranFit.g.d_parser.c"
#include "dparse.h"

D_Reduction d_reduction_0_mlxtranFit = {1, 0, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_1_mlxtranFit = {1, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_2_mlxtranFit = {2, 2, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_3_mlxtranFit = {1, 2, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_4_mlxtranFit = {1, 3, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_5_mlxtranFit = {1, 4, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_6_mlxtranFit = {1, 5, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_7_mlxtranFit = {1, 6, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_10_mlxtranFit = {6, 7, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_11_mlxtranFit = {2, 8, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_12_mlxtranFit = {0, 8, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_13_mlxtranFit = {2, 9, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_14_mlxtranFit = {3, 10, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_15_mlxtranFit = {1, 11, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_18_mlxtranFit = {6, 12, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_19_mlxtranFit = {2, 13, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_20_mlxtranFit = {0, 13, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_21_mlxtranFit = {2, 14, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_22_mlxtranFit = {3, 15, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_23_mlxtranFit = {2, 16, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_27_mlxtranFit = {1, 17, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_28_mlxtranFit = {0, 17, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_29_mlxtranFit = {1, 18, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_30_mlxtranFit = {0, 18, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_31_mlxtranFit = {1, 19, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_32_mlxtranFit = {0, 19, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_33_mlxtranFit = {1, 20, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_34_mlxtranFit = {0, 20, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_35_mlxtranFit = {1, 21, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_38_mlxtranFit = {1, 22, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_39_mlxtranFit = {1, 23, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_40_mlxtranFit = {1, 24, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_41_mlxtranFit = {1, 25, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_42_mlxtranFit = {1, 26, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_43_mlxtranFit = {2, 27, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_44_mlxtranFit = {0, 27, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_45_mlxtranFit = {1, 28, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_47_mlxtranFit = {2, 29, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_0_mlxtranFit = {30, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_1_mlxtranFit = {31, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_2_mlxtranFit = {32, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_3_mlxtranFit = {33, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_4_mlxtranFit = {34, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_5_mlxtranFit = {35, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_6_mlxtranFit = {36, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_7_mlxtranFit = {37, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_8_mlxtranFit = {38, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_9_mlxtranFit = {39, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_10_mlxtranFit = {40, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_11_mlxtranFit = {41, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_12_mlxtranFit = {42, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_13_mlxtranFit = {43, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_14_mlxtranFit = {44, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_15_mlxtranFit = {45, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_16_mlxtranFit = {46, 0, 0, 0, -1, 0, NULL};
D_Shift d_shift_17_mlxtranFit = {47, 0, 0, 0, -2, 0, NULL};
D_Shift d_shift_18_mlxtranFit = {48, 0, 0, 0, -3, 0, NULL};
D_Shift d_shift_19_mlxtranFit = {49, 0, 0, 0, -4, 0, NULL};
D_Shift d_shift_20_mlxtranFit = {50, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_21_mlxtranFit = {51, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_22_mlxtranFit = {52, 0, 0, 0, 0, 0, NULL};

D_Shift * d_accepts_diff_0_0_mlxtranFit[] = {0};
D_Shift ** d_accepts_diff_0_mlxtranFit[] = {
d_accepts_diff_0_0_mlxtranFit
};

unsigned char d_scanner_0_0_0_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_0_0_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_0_1_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_1_1_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_2_1_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_3_1_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_4_1_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_5_1_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_6_1_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_7_mlxtranFit[] = {&d_shift_2_mlxtranFit,NULL};

unsigned char d_scanner_0_8_1_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_9_mlxtranFit[] = {&d_shift_9_mlxtranFit,NULL};

D_Shift * d_accepts_diff_2_0_mlxtranFit[] = {0};
D_Shift ** d_accepts_diff_2_mlxtranFit[] = {
d_accepts_diff_2_0_mlxtranFit
};

unsigned char d_scanner_2_0_0_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 
};

D_Shift * d_shift_2_1_mlxtranFit[] = {&d_shift_3_mlxtranFit,NULL};

D_Shift * d_accepts_diff_7_0_mlxtranFit[] = {0};
D_Shift ** d_accepts_diff_7_mlxtranFit[] = {
d_accepts_diff_7_0_mlxtranFit
};

unsigned char d_scanner_7_0_0_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 
};

D_Shift * d_shift_7_1_mlxtranFit[] = {&d_shift_21_mlxtranFit,NULL};

D_Shift * d_accepts_diff_13_0_mlxtranFit[] = {0};
D_Shift ** d_accepts_diff_13_mlxtranFit[] = {
d_accepts_diff_13_0_mlxtranFit
};

unsigned char d_scanner_13_0_0_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 
};

unsigned char d_scanner_13_1_0_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_13_1_mlxtranFit[] = {&d_shift_20_mlxtranFit,NULL};

D_Shift * d_accepts_diff_14_0_mlxtranFit[] = {0};
D_Shift ** d_accepts_diff_14_mlxtranFit[] = {
d_accepts_diff_14_0_mlxtranFit
};

unsigned char d_scanner_14_0_0_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_14_0_1_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 
0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 0, 0, 0, 0, 
};

unsigned char d_scanner_14_1_0_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
};

unsigned char d_scanner_14_1_1_mlxtranFit[SCANNER_BLOCK_SIZE] = {
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 8, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
};

unsigned char d_scanner_14_1_2_mlxtranFit[SCANNER_BLOCK_SIZE] = {
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
};

unsigned char d_scanner_14_2_0_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
9, 9, 9, 9, 9, 9, 9, 10, 9, 9, 9, 9, 9, 9, 9, 9, 
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
};

unsigned char d_scanner_14_2_1_mlxtranFit[SCANNER_BLOCK_SIZE] = {
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 11, 9, 9, 9, 
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
};

unsigned char d_scanner_14_2_2_mlxtranFit[SCANNER_BLOCK_SIZE] = {
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
};

unsigned char d_scanner_14_3_0_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_14_3_1_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 4, 
0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_14_3_mlxtranFit[] = {&d_shift_19_mlxtranFit,NULL};

D_Shift * d_shift_14_4_mlxtranFit[] = {&d_shift_4_mlxtranFit,NULL};

D_Shift * d_shift_14_6_mlxtranFit[] = {&d_shift_1_mlxtranFit,NULL};

unsigned char d_scanner_14_7_0_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
};

unsigned char d_scanner_14_7_1_mlxtranFit[SCANNER_BLOCK_SIZE] = {
12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
};

D_Shift * d_shift_14_9_mlxtranFit[] = {&d_shift_0_mlxtranFit,NULL};

unsigned char d_scanner_14_10_0_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 
13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 
13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 
13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 
};

unsigned char d_scanner_14_10_1_mlxtranFit[SCANNER_BLOCK_SIZE] = {
13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 
13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 
13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 
13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 
};

D_Shift * d_accepts_diff_17_0_mlxtranFit[] = {0};
D_Shift ** d_accepts_diff_17_mlxtranFit[] = {
d_accepts_diff_17_0_mlxtranFit
};

unsigned char d_scanner_17_0_0_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

unsigned char d_scanner_17_0_1_mlxtranFit[SCANNER_BLOCK_SIZE] = {
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

D_Shift * d_shift_17_0_mlxtranFit[] = {&d_shift_22_mlxtranFit,NULL};

D_Shift * d_accepts_diff_31_0_mlxtranFit[] = {0};
D_Shift ** d_accepts_diff_31_mlxtranFit[] = {
d_accepts_diff_31_0_mlxtranFit
};

unsigned char d_scanner_31_0_1_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 
0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_31_1_0_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 
5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 
5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 
5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 
};

unsigned char d_scanner_31_1_1_mlxtranFit[SCANNER_BLOCK_SIZE] = {
5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 
5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 7, 5, 5, 5, 
5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 
5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 
};

unsigned char d_scanner_31_1_2_mlxtranFit[SCANNER_BLOCK_SIZE] = {
5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 
5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 
5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 
5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 
};

unsigned char d_scanner_31_2_0_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
8, 8, 8, 8, 8, 8, 8, 9, 8, 8, 8, 8, 8, 8, 8, 8, 
8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
};

unsigned char d_scanner_31_2_1_mlxtranFit[SCANNER_BLOCK_SIZE] = {
8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 10, 8, 8, 8, 
8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
};

unsigned char d_scanner_31_2_2_mlxtranFit[SCANNER_BLOCK_SIZE] = {
8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
};

unsigned char d_scanner_31_6_0_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 
11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 
11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 
11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 
};

unsigned char d_scanner_31_6_1_mlxtranFit[SCANNER_BLOCK_SIZE] = {
11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 
11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 
11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 
11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 
};

D_Shift * d_accepts_diff_45_0_mlxtranFit[] = {0};
D_Shift ** d_accepts_diff_45_mlxtranFit[] = {
d_accepts_diff_45_0_mlxtranFit
};

unsigned char d_scanner_45_0_0_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_45_0_1_mlxtranFit[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 
};

D_Shift * d_shift_45_1_mlxtranFit[] = {&d_shift_5_mlxtranFit,NULL};

D_Shift * d_shift_45_2_mlxtranFit[] = {&d_shift_6_mlxtranFit,NULL};

SB_uint8 d_scanner_0_mlxtranFit[10] = {
{NULL, {d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_1_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{NULL, {d_scanner_0_0_0_mlxtranFit, d_scanner_0_1_1_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{NULL, {d_scanner_0_0_0_mlxtranFit, d_scanner_0_2_1_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{NULL, {d_scanner_0_0_0_mlxtranFit, d_scanner_0_3_1_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{NULL, {d_scanner_0_0_0_mlxtranFit, d_scanner_0_4_1_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{NULL, {d_scanner_0_0_0_mlxtranFit, d_scanner_0_5_1_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{NULL, {d_scanner_0_0_0_mlxtranFit, d_scanner_0_6_1_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{d_shift_0_7_mlxtranFit, {d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{NULL, {d_scanner_0_0_0_mlxtranFit, d_scanner_0_8_1_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{d_shift_0_9_mlxtranFit, {d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}}
};

SB_trans_uint8 d_transition_0_mlxtranFit[10] = {
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}}
};

SB_uint8 d_scanner_2_mlxtranFit[2] = {
{NULL, {d_scanner_2_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{d_shift_2_1_mlxtranFit, {d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}}
};

SB_trans_uint8 d_transition_2_mlxtranFit[2] = {
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}}
};

SB_uint8 d_scanner_7_mlxtranFit[2] = {
{NULL, {d_scanner_7_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{d_shift_7_1_mlxtranFit, {d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}}
};

SB_trans_uint8 d_transition_7_mlxtranFit[2] = {
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}}
};

SB_uint8 d_scanner_13_mlxtranFit[3] = {
{NULL, {d_scanner_13_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{d_shift_13_1_mlxtranFit, {d_scanner_13_1_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{d_shift_7_1_mlxtranFit, {d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}}
};

SB_trans_uint8 d_transition_13_mlxtranFit[3] = {
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}}
};

SB_uint8 d_scanner_14_mlxtranFit[13] = {
{NULL, {d_scanner_14_0_0_mlxtranFit, d_scanner_14_0_1_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{NULL, {d_scanner_14_1_0_mlxtranFit, d_scanner_14_1_1_mlxtranFit
 , d_scanner_14_1_2_mlxtranFit, d_scanner_14_1_2_mlxtranFit}},
{NULL, {d_scanner_14_2_0_mlxtranFit, d_scanner_14_2_1_mlxtranFit
 , d_scanner_14_2_2_mlxtranFit, d_scanner_14_2_2_mlxtranFit}},
{d_shift_14_3_mlxtranFit, {d_scanner_14_3_0_mlxtranFit, d_scanner_14_3_1_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{d_shift_14_4_mlxtranFit, {d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{NULL, {d_scanner_14_1_0_mlxtranFit, d_scanner_14_1_1_mlxtranFit
 , d_scanner_14_1_2_mlxtranFit, d_scanner_14_1_2_mlxtranFit}},
{d_shift_14_6_mlxtranFit, {d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{NULL, {d_scanner_14_7_0_mlxtranFit, d_scanner_14_7_1_mlxtranFit
 , d_scanner_14_7_1_mlxtranFit, d_scanner_14_7_1_mlxtranFit}},
{NULL, {d_scanner_14_2_0_mlxtranFit, d_scanner_14_2_1_mlxtranFit
 , d_scanner_14_2_2_mlxtranFit, d_scanner_14_2_2_mlxtranFit}},
{d_shift_14_9_mlxtranFit, {d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{NULL, {d_scanner_14_10_0_mlxtranFit, d_scanner_14_10_1_mlxtranFit
 , d_scanner_14_10_1_mlxtranFit, d_scanner_14_10_1_mlxtranFit}},
{NULL, {d_scanner_14_1_0_mlxtranFit, d_scanner_14_1_1_mlxtranFit
 , d_scanner_14_1_2_mlxtranFit, d_scanner_14_1_2_mlxtranFit}},
{NULL, {d_scanner_14_2_0_mlxtranFit, d_scanner_14_2_1_mlxtranFit
 , d_scanner_14_2_2_mlxtranFit, d_scanner_14_2_2_mlxtranFit}}
};

SB_trans_uint8 d_transition_14_mlxtranFit[13] = {
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}}
};

SB_uint8 d_scanner_17_mlxtranFit[2] = {
{d_shift_17_0_mlxtranFit, {d_scanner_17_0_0_mlxtranFit, d_scanner_17_0_1_mlxtranFit
 , d_scanner_17_0_1_mlxtranFit, d_scanner_17_0_1_mlxtranFit}},
{d_shift_17_0_mlxtranFit, {d_scanner_17_0_0_mlxtranFit, d_scanner_17_0_1_mlxtranFit
 , d_scanner_17_0_1_mlxtranFit, d_scanner_17_0_1_mlxtranFit}}
};

SB_trans_uint8 d_transition_17_mlxtranFit[2] = {
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}}
};

SB_uint8 d_scanner_31_mlxtranFit[12] = {
{NULL, {d_scanner_14_0_0_mlxtranFit, d_scanner_31_0_1_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{NULL, {d_scanner_31_1_0_mlxtranFit, d_scanner_31_1_1_mlxtranFit
 , d_scanner_31_1_2_mlxtranFit, d_scanner_31_1_2_mlxtranFit}},
{NULL, {d_scanner_31_2_0_mlxtranFit, d_scanner_31_2_1_mlxtranFit
 , d_scanner_31_2_2_mlxtranFit, d_scanner_31_2_2_mlxtranFit}},
{d_shift_14_3_mlxtranFit, {d_scanner_14_3_0_mlxtranFit, d_scanner_14_3_1_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{NULL, {d_scanner_31_1_0_mlxtranFit, d_scanner_31_1_1_mlxtranFit
 , d_scanner_31_1_2_mlxtranFit, d_scanner_31_1_2_mlxtranFit}},
{d_shift_14_6_mlxtranFit, {d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{NULL, {d_scanner_31_6_0_mlxtranFit, d_scanner_31_6_1_mlxtranFit
 , d_scanner_31_6_1_mlxtranFit, d_scanner_31_6_1_mlxtranFit}},
{NULL, {d_scanner_31_2_0_mlxtranFit, d_scanner_31_2_1_mlxtranFit
 , d_scanner_31_2_2_mlxtranFit, d_scanner_31_2_2_mlxtranFit}},
{d_shift_14_9_mlxtranFit, {d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{NULL, {d_scanner_14_7_0_mlxtranFit, d_scanner_14_7_1_mlxtranFit
 , d_scanner_14_7_1_mlxtranFit, d_scanner_14_7_1_mlxtranFit}},
{NULL, {d_scanner_31_1_0_mlxtranFit, d_scanner_31_1_1_mlxtranFit
 , d_scanner_31_1_2_mlxtranFit, d_scanner_31_1_2_mlxtranFit}},
{NULL, {d_scanner_31_2_0_mlxtranFit, d_scanner_31_2_1_mlxtranFit
 , d_scanner_31_2_2_mlxtranFit, d_scanner_31_2_2_mlxtranFit}}
};

SB_trans_uint8 d_transition_31_mlxtranFit[12] = {
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}}
};

SB_uint8 d_scanner_45_mlxtranFit[3] = {
{NULL, {d_scanner_45_0_0_mlxtranFit, d_scanner_45_0_1_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{d_shift_45_1_mlxtranFit, {d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}},
{d_shift_45_2_mlxtranFit, {d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit
 , d_scanner_0_0_0_mlxtranFit, d_scanner_0_0_0_mlxtranFit}}
};

SB_trans_uint8 d_transition_45_mlxtranFit[3] = {
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}},
{{d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit
 , d_accepts_diff_0_0_0_mlxtranFit, d_accepts_diff_0_0_0_mlxtranFit}}
};

unsigned char d_goto_valid_0_mlxtranFit[] = {
0x8e,0x94,0x1,0x0,0x81,0x0,0x0};
unsigned char d_goto_valid_1_mlxtranFit[] = {
0x0,0x0,0x0,0xc,0x0,0x0,0x0};
D_Reduction * d_reductions_1_mlxtranFit[] = {&d_reduction_44_mlxtranFit};
D_RightEpsilonHint d_right_epsilon_hints_1_mlxtranFit[] = {{0, 13, &d_reduction_42_mlxtranFit}};
unsigned char d_goto_valid_2_mlxtranFit[] = {
0x0,0x0,0x0,0x0,0x2,0x0,0x0};
unsigned char d_goto_valid_3_mlxtranFit[] = {
0x0,0x0,0x0,0x0,0x2,0x0,0x0};
unsigned char d_goto_valid_5_mlxtranFit[] = {
0x88,0x94,0x1,0x0,0x81,0x0,0x0};
D_Reduction * d_reductions_5_mlxtranFit[] = {&d_reduction_1_mlxtranFit};
D_Reduction * d_reductions_6_mlxtranFit[] = {&d_reduction_3_mlxtranFit};
unsigned char d_goto_valid_7_mlxtranFit[] = {
0x0,0x0,0x10,0x20,0x0,0x0,0x8};
D_Reduction * d_reductions_7_mlxtranFit[] = {&d_reduction_34_mlxtranFit};
D_RightEpsilonHint d_right_epsilon_hints_7_mlxtranFit[] = {{0, 18, &d_reduction_23_mlxtranFit}};
unsigned char d_goto_valid_8_mlxtranFit[] = {
0x0,0x0,0x2,0x20,0x0,0x0,0x8};
D_Reduction * d_reductions_8_mlxtranFit[] = {&d_reduction_28_mlxtranFit};
D_RightEpsilonHint d_right_epsilon_hints_8_mlxtranFit[] = {{0, 20, &d_reduction_23_mlxtranFit}};
unsigned char d_goto_valid_9_mlxtranFit[] = {
0x0,0x0,0x8,0x20,0x0,0x0,0x8};
D_Reduction * d_reductions_9_mlxtranFit[] = {&d_reduction_32_mlxtranFit};
D_RightEpsilonHint d_right_epsilon_hints_9_mlxtranFit[] = {{0, 22, &d_reduction_23_mlxtranFit}};
unsigned char d_goto_valid_10_mlxtranFit[] = {
0x0,0x0,0x4,0x20,0x0,0x0,0x8};
D_Reduction * d_reductions_10_mlxtranFit[] = {&d_reduction_30_mlxtranFit};
D_RightEpsilonHint d_right_epsilon_hints_10_mlxtranFit[] = {{0, 24, &d_reduction_23_mlxtranFit}};
D_Reduction * d_reductions_11_mlxtranFit[] = {&d_reduction_4_mlxtranFit};
unsigned char d_goto_valid_13_mlxtranFit[] = {
0x0,0x0,0x0,0x30,0x0,0x0,0xc};
D_Reduction * d_reductions_13_mlxtranFit[] = {&d_reduction_42_mlxtranFit};
unsigned char d_goto_valid_14_mlxtranFit[] = {
0x70,0x0,0x0,0xc2,0x4,0x0,0x2};
unsigned char d_goto_valid_15_mlxtranFit[] = {
0x30,0x8,0x0,0xc2,0x4,0x0,0x2};
D_Reduction * d_reductions_16_mlxtranFit[] = {&d_reduction_2_mlxtranFit};
unsigned char d_goto_valid_17_mlxtranFit[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x10};
D_Reduction * d_reductions_18_mlxtranFit[] = {&d_reduction_23_mlxtranFit};
D_Reduction * d_reductions_19_mlxtranFit[] = {&d_reduction_33_mlxtranFit};
D_Reduction * d_reductions_20_mlxtranFit[] = {&d_reduction_23_mlxtranFit};
D_Reduction * d_reductions_21_mlxtranFit[] = {&d_reduction_27_mlxtranFit};
D_Reduction * d_reductions_22_mlxtranFit[] = {&d_reduction_23_mlxtranFit};
D_Reduction * d_reductions_23_mlxtranFit[] = {&d_reduction_31_mlxtranFit};
D_Reduction * d_reductions_24_mlxtranFit[] = {&d_reduction_23_mlxtranFit};
D_Reduction * d_reductions_25_mlxtranFit[] = {&d_reduction_29_mlxtranFit};
D_Reduction * d_reductions_26_mlxtranFit[] = {&d_reduction_45_mlxtranFit};
D_Reduction * d_reductions_27_mlxtranFit[] = {&d_reduction_43_mlxtranFit};
D_Reduction * d_reductions_28_mlxtranFit[] = {&d_reduction_45_mlxtranFit};
D_Reduction * d_reductions_29_mlxtranFit[] = {&d_reduction_5_mlxtranFit};
D_Reduction * d_reductions_30_mlxtranFit[] = {&d_reduction_6_mlxtranFit};
unsigned char d_goto_valid_31_mlxtranFit[] = {
0x70,0x0,0x0,0xc2,0x0,0x0,0x2};
D_Reduction * d_reductions_32_mlxtranFit[] = {&d_reduction_41_mlxtranFit};
D_Reduction * d_reductions_33_mlxtranFit[] = {&d_reduction_7_mlxtranFit};
D_Reduction * d_reductions_34_mlxtranFit[] = {&d_reduction_7_mlxtranFit};
D_Reduction * d_reductions_35_mlxtranFit[] = {&d_reduction_14_mlxtranFit};
D_Reduction * d_reductions_36_mlxtranFit[] = {&d_reduction_7_mlxtranFit};
unsigned char d_goto_valid_37_mlxtranFit[] = {
0x30,0x8,0x0,0xc2,0x0,0x0,0x2};
D_Reduction * d_reductions_38_mlxtranFit[] = {&d_reduction_15_mlxtranFit};
D_Reduction * d_reductions_39_mlxtranFit[] = {&d_reduction_15_mlxtranFit};
D_Reduction * d_reductions_40_mlxtranFit[] = {&d_reduction_22_mlxtranFit};
D_Reduction * d_reductions_41_mlxtranFit[] = {&d_reduction_15_mlxtranFit};
D_Reduction * d_reductions_42_mlxtranFit[] = {&d_reduction_47_mlxtranFit};
unsigned char d_goto_valid_43_mlxtranFit[] = {
0x0,0x1,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_43_mlxtranFit[] = {&d_reduction_12_mlxtranFit};
unsigned char d_goto_valid_44_mlxtranFit[] = {
0x0,0x20,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_44_mlxtranFit[] = {&d_reduction_20_mlxtranFit};
unsigned char d_goto_valid_45_mlxtranFit[] = {
0x0,0x2,0x0,0x0,0x18,0x0,0x0};
unsigned char d_goto_valid_46_mlxtranFit[] = {
0x0,0x40,0x0,0x0,0x18,0x0,0x0};
unsigned char d_goto_valid_47_mlxtranFit[] = {
0x70,0x0,0x0,0xc2,0x0,0x0,0x2};
D_Reduction * d_reductions_48_mlxtranFit[] = {&d_reduction_10_mlxtranFit};
D_Reduction * d_reductions_49_mlxtranFit[] = {&d_reduction_11_mlxtranFit};
unsigned char d_goto_valid_50_mlxtranFit[] = {
0x30,0x8,0x0,0xc2,0x0,0x0,0x2};
D_Reduction * d_reductions_51_mlxtranFit[] = {&d_reduction_18_mlxtranFit};
D_Reduction * d_reductions_52_mlxtranFit[] = {&d_reduction_19_mlxtranFit};
D_Reduction * d_reductions_53_mlxtranFit[] = {&d_reduction_13_mlxtranFit};
D_Reduction * d_reductions_54_mlxtranFit[] = {&d_reduction_21_mlxtranFit};
unsigned short d_gotos_mlxtranFit[146] = {
5,6,7,13,14,15,8,16,19,9,21,10,17,23,11,12,
8,20,25,9,43,10,22,24,11,12,46,28,29,26,47,3,
34,35,36,53,0,0,4,18,0,3,0,50,18,18,0,0,
4,27,18,18,0,37,39,40,51,52,30,31,0,41,32,0,
34,35,44,39,40,48,49,34,35,54,45,42,0,33,0,0,
30,31,0,0,38,37,0,0,42,0,30,31,37,30,31,0,
0,30,31,33,39,40,0,0,0,0,0,55,0,33,0,0,
33,0,0,0,33,0,0,0,0,42,0,0,0,0,30,31,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,33};

D_ErrorRecoveryHint d_error_recovery_hints_0_mlxtranFit[] = {{0, 7, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_2_mlxtranFit[] = {{1, 7, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_3_mlxtranFit[] = {{1, 12, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_14_mlxtranFit[] = {{2, 7, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_15_mlxtranFit[] = {{2, 12, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_31_mlxtranFit[] = {{3, 7, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_37_mlxtranFit[] = {{3, 12, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_43_mlxtranFit[] = {{4, 7, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_44_mlxtranFit[] = {{4, 12, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_45_mlxtranFit[] = {{5, 7, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_46_mlxtranFit[] = {{5, 12, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_48_mlxtranFit[] = {{6, 7, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_51_mlxtranFit[] = {{6, 12, "}"}};

D_State d_states_mlxtranFit[] = {
{d_goto_valid_0_mlxtranFit, 1, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_0_mlxtranFit}, 1, NULL, (void*)d_scanner_0_mlxtranFit, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_mlxtranFit, d_accepts_diff_0_mlxtranFit, -1},
{d_goto_valid_1_mlxtranFit, 23, {1, d_reductions_1_mlxtranFit}, {1, d_right_epsilon_hints_1_mlxtranFit}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_2_mlxtranFit, 28, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_2_mlxtranFit}, 1, NULL, (void*)d_scanner_2_mlxtranFit, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_2_mlxtranFit, d_accepts_diff_2_mlxtranFit, -1},
{d_goto_valid_3_mlxtranFit, 26, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_3_mlxtranFit}, 1, NULL, (void*)d_scanner_2_mlxtranFit, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_2_mlxtranFit, d_accepts_diff_2_mlxtranFit, -1},
{NULL, -2147483647, {0, NULL}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 1, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_5_mlxtranFit, -9, {1, d_reductions_5_mlxtranFit}, {0, NULL}, {1, d_error_recovery_hints_0_mlxtranFit}, 1, NULL, (void*)d_scanner_0_mlxtranFit, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_mlxtranFit, d_accepts_diff_0_mlxtranFit, -1},
{NULL, -2147483647, {1, d_reductions_6_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_7_mlxtranFit, 12, {1, d_reductions_7_mlxtranFit}, {1, d_right_epsilon_hints_7_mlxtranFit}, {0, NULL}, 1, NULL, (void*)d_scanner_7_mlxtranFit, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_7_mlxtranFit, d_accepts_diff_7_mlxtranFit, -1},
{d_goto_valid_8_mlxtranFit, 7, {1, d_reductions_8_mlxtranFit}, {1, d_right_epsilon_hints_8_mlxtranFit}, {0, NULL}, 1, NULL, (void*)d_scanner_7_mlxtranFit, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_7_mlxtranFit, d_accepts_diff_7_mlxtranFit, -1},
{d_goto_valid_9_mlxtranFit, 6, {1, d_reductions_9_mlxtranFit}, {1, d_right_epsilon_hints_9_mlxtranFit}, {0, NULL}, 1, NULL, (void*)d_scanner_7_mlxtranFit, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_7_mlxtranFit, d_accepts_diff_7_mlxtranFit, -1},
{d_goto_valid_10_mlxtranFit, 0, {1, d_reductions_10_mlxtranFit}, {1, d_right_epsilon_hints_10_mlxtranFit}, {0, NULL}, 1, NULL, (void*)d_scanner_7_mlxtranFit, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_7_mlxtranFit, d_accepts_diff_7_mlxtranFit, -1},
{NULL, -2147483647, {1, d_reductions_11_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {0, NULL}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 1, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_13_mlxtranFit, 1, {1, d_reductions_13_mlxtranFit}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_13_mlxtranFit, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_13_mlxtranFit, d_accepts_diff_13_mlxtranFit, -1},
{d_goto_valid_14_mlxtranFit, -28, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_14_mlxtranFit}, 1, NULL, (void*)d_scanner_14_mlxtranFit, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_14_mlxtranFit, d_accepts_diff_14_mlxtranFit, -1},
{d_goto_valid_15_mlxtranFit, -50, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_15_mlxtranFit}, 1, NULL, (void*)d_scanner_14_mlxtranFit, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_14_mlxtranFit, d_accepts_diff_14_mlxtranFit, -1},
{NULL, -2147483647, {1, d_reductions_16_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_17_mlxtranFit, 32, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_17_mlxtranFit, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_17_mlxtranFit, d_accepts_diff_17_mlxtranFit, -1},
{NULL, -2147483647, {1, d_reductions_18_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_19_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_20_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_21_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_22_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_23_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_24_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_25_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_26_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_27_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_28_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_29_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_30_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_31_mlxtranFit, -60, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_31_mlxtranFit}, 1, NULL, (void*)d_scanner_31_mlxtranFit, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_31_mlxtranFit, d_accepts_diff_31_mlxtranFit, -1},
{NULL, -2147483647, {1, d_reductions_32_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_33_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_34_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_35_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_36_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_37_mlxtranFit, -63, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_37_mlxtranFit}, 1, NULL, (void*)d_scanner_31_mlxtranFit, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_31_mlxtranFit, d_accepts_diff_31_mlxtranFit, -1},
{NULL, -2147483647, {1, d_reductions_38_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_39_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_40_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_41_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_42_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_43_mlxtranFit, -18, {1, d_reductions_43_mlxtranFit}, {0, NULL}, {1, d_error_recovery_hints_43_mlxtranFit}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_44_mlxtranFit, -17, {1, d_reductions_44_mlxtranFit}, {0, NULL}, {1, d_error_recovery_hints_44_mlxtranFit}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_45_mlxtranFit, -34, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_45_mlxtranFit}, 1, NULL, (void*)d_scanner_45_mlxtranFit, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_45_mlxtranFit, d_accepts_diff_45_mlxtranFit, -1},
{d_goto_valid_46_mlxtranFit, -21, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_46_mlxtranFit}, 1, NULL, (void*)d_scanner_45_mlxtranFit, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_45_mlxtranFit, d_accepts_diff_45_mlxtranFit, -1},
{d_goto_valid_47_mlxtranFit, -67, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_31_mlxtranFit, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_31_mlxtranFit, d_accepts_diff_31_mlxtranFit, -1},
{NULL, -2147483647, {1, d_reductions_48_mlxtranFit}, {0, NULL}, {1, d_error_recovery_hints_48_mlxtranFit}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_49_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_50_mlxtranFit, -96, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_31_mlxtranFit, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_31_mlxtranFit, d_accepts_diff_31_mlxtranFit, -1},
{NULL, -2147483647, {1, d_reductions_51_mlxtranFit}, {0, NULL}, {1, d_error_recovery_hints_51_mlxtranFit}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_52_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_53_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_54_mlxtranFit}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1}
};

D_Symbol d_symbols_mlxtranFit[] = {
{D_SYMBOL_EBNF, "0 Start", 7, -1},
{D_SYMBOL_NTERM, "statement_list", 14, -1},
{D_SYMBOL_INTERNAL, "statement_list__3", 17, -1},
{D_SYMBOL_EBNF, "statement_list__2", 17, -1},
{D_SYMBOL_NTERM, "char_t1", 7, -1},
{D_SYMBOL_NTERM, "char_t2", 7, -1},
{D_SYMBOL_NTERM, "datId", 5, -1},
{D_SYMBOL_NTERM, "dataLine", 8, -1},
{D_SYMBOL_INTERNAL, "dataLine__9", 11, -1},
{D_SYMBOL_EBNF, "dataLine__8", 11, -1},
{D_SYMBOL_NTERM, "dataLine1", 9, -1},
{D_SYMBOL_NTERM, "modelId", 7, -1},
{D_SYMBOL_NTERM, "modelLine", 9, -1},
{D_SYMBOL_INTERNAL, "modelLine__14", 13, -1},
{D_SYMBOL_EBNF, "modelLine__13", 13, -1},
{D_SYMBOL_NTERM, "modelLine1", 10, -1},
{D_SYMBOL_NTERM, "statement", 9, -1},
{D_SYMBOL_INTERNAL, "statement__20", 13, -1},
{D_SYMBOL_INTERNAL, "statement__19", 13, -1},
{D_SYMBOL_INTERNAL, "statement__18", 13, -1},
{D_SYMBOL_INTERNAL, "statement__17", 13, -1},
{D_SYMBOL_NTERM, "constant", 8, -1},
{D_SYMBOL_NTERM, "decimalint", 10, -1},
{D_SYMBOL_NTERM, "float1", 6, -1},
{D_SYMBOL_NTERM, "float2", 6, -1},
{D_SYMBOL_NTERM, "identifier", 10, -1},
{D_SYMBOL_NTERM, "whitespace", 10, 1},
{D_SYMBOL_INTERNAL, "whitespace__28", 14, -1},
{D_SYMBOL_EBNF, "whitespace__27", 14, -1},
{D_SYMBOL_NTERM, "singleLineComment", 17, -1},
{D_SYMBOL_REGEX, "\\\\'([^\\\\'\\\\\\\\]|\\\\\\\\[^])*\\\\'", 41, -1},
{D_SYMBOL_REGEX, "\\\"([^\\\"\\\\\\\\]|\\\\\\\\[^])*\\\"", 38, -1},
{D_SYMBOL_STRING, "data", 4, -1},
{D_SYMBOL_STRING, "=", 1, -1},
{D_SYMBOL_STRING, "{", 1, -1},
{D_SYMBOL_STRING, ",", 1, -1},
{D_SYMBOL_STRING, "}", 1, -1},
{D_SYMBOL_STRING, "data", 4, -1},
{D_SYMBOL_STRING, "=", 1, -1},
{D_SYMBOL_STRING, "model", 5, -1},
{D_SYMBOL_STRING, "=", 1, -1},
{D_SYMBOL_STRING, "{", 1, -1},
{D_SYMBOL_STRING, ",", 1, -1},
{D_SYMBOL_STRING, "}", 1, -1},
{D_SYMBOL_STRING, "model", 5, -1},
{D_SYMBOL_STRING, "=", 1, -1},
{D_SYMBOL_REGEX, "0|([1-9][0-9]*)", 15, -1},
{D_SYMBOL_REGEX, "([0-9]+.[0-9]*|[0-9]*.[0-9]+)([eE][\\\\-\\\\+]?[0-9]+)?", 55, -1},
{D_SYMBOL_REGEX, "[0-9]+[eE][\\\\-\\\\+]?[0-9]+", 29, -1},
{D_SYMBOL_REGEX, "[a-zA-Z][a-zA-Z0-9_]*", 21, -1},
{D_SYMBOL_REGEX, "[ \\t\\r\\n]+", 13, -1},
{D_SYMBOL_REGEX, "[;]", 3, -1},
{D_SYMBOL_REGEX, "[^\\n]*", 7, -1},
};

D_ParserTables parser_tables_mlxtranFit = {
55, d_states_mlxtranFit, d_gotos_mlxtranFit, 1, 53, d_symbols_mlxtranFit, NULL, 0, NULL, 0};
