#include <R.h>
#include <Rinternals.h>
#define printf Rprintf

/*
  Generated by Make DParser Version 1.31.4ab9d43046e5d22ffb365ec5f5184a7cfee09b30
  Available at https://github.com/jplevyak/dparser
*/

#line 7 "/home/matt/src/monolix2rx/src/mlxtranTask.g.d_parser.c"
#include "dparse.h"

D_Reduction d_reduction_0_mlxtranTask = {1, 0, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_1_mlxtranTask = {1, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_2_mlxtranTask = {2, 2, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_3_mlxtranTask = {1, 2, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_4_mlxtranTask = {1, 3, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_5_mlxtranTask = {1, 4, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_6_mlxtranTask = {6, 5, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_7_mlxtranTask = {2, 6, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_8_mlxtranTask = {0, 6, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_9_mlxtranTask = {2, 7, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_10_mlxtranTask = {3, 8, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_11_mlxtranTask = {1, 9, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_13_mlxtranTask = {1, 10, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_14_mlxtranTask = {5, 11, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_15_mlxtranTask = {2, 12, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_16_mlxtranTask = {0, 12, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_17_mlxtranTask = {2, 13, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_18_mlxtranTask = {1, 14, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_19_mlxtranTask = {0, 14, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_20_mlxtranTask = {2, 15, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_21_mlxtranTask = {1, 16, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_22_mlxtranTask = {0, 16, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_23_mlxtranTask = {1, 17, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_26_mlxtranTask = {1, 18, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_27_mlxtranTask = {1, 19, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_28_mlxtranTask = {1, 20, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_29_mlxtranTask = {1, 21, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_30_mlxtranTask = {1, 22, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_31_mlxtranTask = {2, 23, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_32_mlxtranTask = {0, 23, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_33_mlxtranTask = {1, 24, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_35_mlxtranTask = {2, 25, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_0_mlxtranTask = {26, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_1_mlxtranTask = {27, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_2_mlxtranTask = {28, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_3_mlxtranTask = {29, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_4_mlxtranTask = {30, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_5_mlxtranTask = {31, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_6_mlxtranTask = {32, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_7_mlxtranTask = {33, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_8_mlxtranTask = {34, 0, 0, 0, -1, 0, NULL};
D_Shift d_shift_9_mlxtranTask = {35, 0, 0, 0, -2, 0, NULL};
D_Shift d_shift_10_mlxtranTask = {36, 0, 0, 0, -3, 0, NULL};
D_Shift d_shift_11_mlxtranTask = {37, 0, 0, 0, -4, 0, NULL};
D_Shift d_shift_12_mlxtranTask = {38, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_13_mlxtranTask = {39, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_14_mlxtranTask = {40, 0, 0, 0, 0, 0, NULL};

D_Shift * d_accepts_diff_0_0_mlxtranTask[] = {0};
D_Shift ** d_accepts_diff_0_mlxtranTask[] = {
d_accepts_diff_0_0_mlxtranTask
};

unsigned char d_scanner_0_0_0_mlxtranTask[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_0_0_mlxtranTask[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_0_1_mlxtranTask[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_1_0_mlxtranTask[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_1_1_mlxtranTask[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_1_mlxtranTask[] = {&d_shift_11_mlxtranTask,NULL};

D_Shift * d_accepts_diff_6_0_mlxtranTask[] = {0};
D_Shift ** d_accepts_diff_6_mlxtranTask[] = {
d_accepts_diff_6_0_mlxtranTask
};

unsigned char d_scanner_6_0_0_mlxtranTask[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_6_1_mlxtranTask[] = {&d_shift_5_mlxtranTask,NULL};

D_Shift * d_accepts_diff_7_0_mlxtranTask[] = {0};
D_Shift ** d_accepts_diff_7_mlxtranTask[] = {
d_accepts_diff_7_0_mlxtranTask
};

unsigned char d_scanner_7_0_0_mlxtranTask[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 
};

D_Shift * d_shift_7_1_mlxtranTask[] = {&d_shift_13_mlxtranTask,NULL};

D_Shift * d_accepts_diff_11_0_mlxtranTask[] = {0};
D_Shift ** d_accepts_diff_11_mlxtranTask[] = {
d_accepts_diff_11_0_mlxtranTask
};

unsigned char d_scanner_11_0_0_mlxtranTask[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 
};

unsigned char d_scanner_11_1_0_mlxtranTask[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_11_1_mlxtranTask[] = {&d_shift_12_mlxtranTask,NULL};

D_Shift * d_accepts_diff_14_0_mlxtranTask[] = {0};
D_Shift ** d_accepts_diff_14_mlxtranTask[] = {
d_accepts_diff_14_0_mlxtranTask
};

unsigned char d_scanner_14_0_0_mlxtranTask[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

unsigned char d_scanner_14_0_1_mlxtranTask[SCANNER_BLOCK_SIZE] = {
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

D_Shift * d_shift_14_0_mlxtranTask[] = {&d_shift_14_mlxtranTask,NULL};

D_Shift * d_accepts_diff_24_0_mlxtranTask[] = {0};
D_Shift ** d_accepts_diff_24_mlxtranTask[] = {
d_accepts_diff_24_0_mlxtranTask
};

unsigned char d_scanner_24_0_0_mlxtranTask[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 
};

D_Shift * d_shift_24_1_mlxtranTask[] = {&d_shift_0_mlxtranTask,NULL};

D_Shift * d_accepts_diff_26_0_mlxtranTask[] = {0};
D_Shift ** d_accepts_diff_26_mlxtranTask[] = {
d_accepts_diff_26_0_mlxtranTask
};

unsigned char d_scanner_26_0_0_mlxtranTask[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 3, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_26_1_mlxtranTask[] = {&d_shift_7_mlxtranTask,NULL};

D_Shift * d_shift_26_2_mlxtranTask[] = {&d_shift_2_mlxtranTask,NULL};

D_Shift * d_accepts_diff_27_0_mlxtranTask[] = {0};
D_Shift ** d_accepts_diff_27_mlxtranTask[] = {
d_accepts_diff_27_0_mlxtranTask
};

unsigned char d_scanner_27_0_1_mlxtranTask[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 0, 0, 0, 0, 
};

D_Shift * d_shift_27_2_mlxtranTask[] = {&d_shift_1_mlxtranTask,NULL};

D_Shift * d_accepts_diff_36_0_mlxtranTask[] = {0};
D_Shift ** d_accepts_diff_36_mlxtranTask[] = {
d_accepts_diff_36_0_mlxtranTask
};

unsigned char d_scanner_36_0_0_mlxtranTask[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_36_0_1_mlxtranTask[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 
};

D_Shift * d_shift_36_2_mlxtranTask[] = {&d_shift_3_mlxtranTask,NULL};

SB_uint8 d_scanner_0_mlxtranTask[2] = {
{NULL, {d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_1_mlxtranTask
 , d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask}},
{d_shift_0_1_mlxtranTask, {d_scanner_0_1_0_mlxtranTask, d_scanner_0_1_1_mlxtranTask
 , d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask}}
};

SB_trans_uint8 d_transition_0_mlxtranTask[2] = {
{{d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask
 , d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask}},
{{d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask
 , d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask}}
};

SB_uint8 d_scanner_6_mlxtranTask[2] = {
{NULL, {d_scanner_6_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask
 , d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask}},
{d_shift_6_1_mlxtranTask, {d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask
 , d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask}}
};

SB_trans_uint8 d_transition_6_mlxtranTask[2] = {
{{d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask
 , d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask}},
{{d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask
 , d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask}}
};

SB_uint8 d_scanner_7_mlxtranTask[2] = {
{NULL, {d_scanner_7_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask
 , d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask}},
{d_shift_7_1_mlxtranTask, {d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask
 , d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask}}
};

SB_trans_uint8 d_transition_7_mlxtranTask[2] = {
{{d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask
 , d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask}},
{{d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask
 , d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask}}
};

SB_uint8 d_scanner_11_mlxtranTask[3] = {
{NULL, {d_scanner_11_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask
 , d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask}},
{d_shift_11_1_mlxtranTask, {d_scanner_11_1_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask
 , d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask}},
{d_shift_7_1_mlxtranTask, {d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask
 , d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask}}
};

SB_trans_uint8 d_transition_11_mlxtranTask[3] = {
{{d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask
 , d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask}},
{{d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask
 , d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask}},
{{d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask
 , d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask}}
};

SB_uint8 d_scanner_14_mlxtranTask[2] = {
{d_shift_14_0_mlxtranTask, {d_scanner_14_0_0_mlxtranTask, d_scanner_14_0_1_mlxtranTask
 , d_scanner_14_0_1_mlxtranTask, d_scanner_14_0_1_mlxtranTask}},
{d_shift_14_0_mlxtranTask, {d_scanner_14_0_0_mlxtranTask, d_scanner_14_0_1_mlxtranTask
 , d_scanner_14_0_1_mlxtranTask, d_scanner_14_0_1_mlxtranTask}}
};

SB_trans_uint8 d_transition_14_mlxtranTask[2] = {
{{d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask
 , d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask}},
{{d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask
 , d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask}}
};

SB_uint8 d_scanner_24_mlxtranTask[2] = {
{NULL, {d_scanner_24_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask
 , d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask}},
{d_shift_24_1_mlxtranTask, {d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask
 , d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask}}
};

SB_trans_uint8 d_transition_24_mlxtranTask[2] = {
{{d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask
 , d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask}},
{{d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask
 , d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask}}
};

SB_uint8 d_scanner_26_mlxtranTask[3] = {
{NULL, {d_scanner_26_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask
 , d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask}},
{d_shift_26_1_mlxtranTask, {d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask
 , d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask}},
{d_shift_26_2_mlxtranTask, {d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask
 , d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask}}
};

SB_trans_uint8 d_transition_26_mlxtranTask[3] = {
{{d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask
 , d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask}},
{{d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask
 , d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask}},
{{d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask
 , d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask}}
};

SB_uint8 d_scanner_27_mlxtranTask[3] = {
{NULL, {d_scanner_0_0_0_mlxtranTask, d_scanner_27_0_1_mlxtranTask
 , d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask}},
{d_shift_0_1_mlxtranTask, {d_scanner_0_1_0_mlxtranTask, d_scanner_0_1_1_mlxtranTask
 , d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask}},
{d_shift_27_2_mlxtranTask, {d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask
 , d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask}}
};

SB_trans_uint8 d_transition_27_mlxtranTask[3] = {
{{d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask
 , d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask}},
{{d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask
 , d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask}},
{{d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask
 , d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask}}
};

SB_uint8 d_scanner_36_mlxtranTask[3] = {
{NULL, {d_scanner_36_0_0_mlxtranTask, d_scanner_36_0_1_mlxtranTask
 , d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask}},
{d_shift_26_2_mlxtranTask, {d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask
 , d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask}},
{d_shift_36_2_mlxtranTask, {d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask
 , d_scanner_0_0_0_mlxtranTask, d_scanner_0_0_0_mlxtranTask}}
};

SB_trans_uint8 d_transition_36_mlxtranTask[3] = {
{{d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask
 , d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask}},
{{d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask
 , d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask}},
{{d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask
 , d_accepts_diff_0_0_0_mlxtranTask, d_accepts_diff_0_0_0_mlxtranTask}}
};

unsigned char d_goto_valid_0_mlxtranTask[] = {
0xe,0x8c,0x20,0x0,0x20,0x0};
unsigned char d_goto_valid_1_mlxtranTask[] = {
0x0,0x0,0xc0,0x0,0x0,0x0};
D_Reduction * d_reductions_1_mlxtranTask[] = {&d_reduction_32_mlxtranTask};
D_RightEpsilonHint d_right_epsilon_hints_1_mlxtranTask[] = {{0, 11, &d_reduction_30_mlxtranTask}};
D_Reduction * d_reductions_2_mlxtranTask[] = {&d_reduction_29_mlxtranTask};
unsigned char d_goto_valid_4_mlxtranTask[] = {
0x8,0x8c,0x20,0x0,0x20,0x0};
D_Reduction * d_reductions_4_mlxtranTask[] = {&d_reduction_1_mlxtranTask};
D_Reduction * d_reductions_5_mlxtranTask[] = {&d_reduction_3_mlxtranTask};
unsigned char d_goto_valid_6_mlxtranTask[] = {
0x0,0x0,0x0,0x80,0x0,0x0};
unsigned char d_goto_valid_7_mlxtranTask[] = {
0x0,0x0,0x1,0x2,0x80,0x0};
D_Reduction * d_reductions_7_mlxtranTask[] = {&d_reduction_22_mlxtranTask};
D_RightEpsilonHint d_right_epsilon_hints_7_mlxtranTask[] = {{0, 15, &d_reduction_20_mlxtranTask}};
D_Reduction * d_reductions_8_mlxtranTask[] = {&d_reduction_4_mlxtranTask};
D_Reduction * d_reductions_9_mlxtranTask[] = {&d_reduction_13_mlxtranTask};
unsigned char d_goto_valid_11_mlxtranTask[] = {
0x0,0x0,0x0,0x3,0xc0,0x0};
D_Reduction * d_reductions_11_mlxtranTask[] = {&d_reduction_30_mlxtranTask};
D_Reduction * d_reductions_12_mlxtranTask[] = {&d_reduction_2_mlxtranTask};
unsigned char d_goto_valid_13_mlxtranTask[] = {
0x20,0x43,0x20,0x0,0x20,0x0};
D_Reduction * d_reductions_13_mlxtranTask[] = {&d_reduction_19_mlxtranTask};
unsigned char d_goto_valid_14_mlxtranTask[] = {
0x0,0x0,0x0,0x0,0x0,0x1};
D_Reduction * d_reductions_15_mlxtranTask[] = {&d_reduction_20_mlxtranTask};
D_Reduction * d_reductions_16_mlxtranTask[] = {&d_reduction_21_mlxtranTask};
D_Reduction * d_reductions_17_mlxtranTask[] = {&d_reduction_33_mlxtranTask};
D_Reduction * d_reductions_18_mlxtranTask[] = {&d_reduction_31_mlxtranTask};
D_Reduction * d_reductions_19_mlxtranTask[] = {&d_reduction_33_mlxtranTask};
D_Reduction * d_reductions_20_mlxtranTask[] = {&d_reduction_11_mlxtranTask};
D_Reduction * d_reductions_21_mlxtranTask[] = {&d_reduction_11_mlxtranTask};
D_Reduction * d_reductions_22_mlxtranTask[] = {&d_reduction_18_mlxtranTask};
unsigned char d_goto_valid_23_mlxtranTask[] = {
0x0,0x10,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_23_mlxtranTask[] = {&d_reduction_16_mlxtranTask};
unsigned char d_goto_valid_24_mlxtranTask[] = {
0x0,0x0,0x0,0x4,0x0,0x0};
D_Reduction * d_reductions_25_mlxtranTask[] = {&d_reduction_35_mlxtranTask};
unsigned char d_goto_valid_26_mlxtranTask[] = {
0x0,0x20,0x0,0x10,0x2,0x0};
unsigned char d_goto_valid_27_mlxtranTask[] = {
0x10,0x0,0x20,0x8,0x20,0x0};
unsigned char d_goto_valid_28_mlxtranTask[] = {
0x20,0x3,0x20,0x0,0x20,0x0};
D_Reduction * d_reductions_29_mlxtranTask[] = {&d_reduction_14_mlxtranTask};
D_Reduction * d_reductions_30_mlxtranTask[] = {&d_reduction_15_mlxtranTask};
unsigned char d_goto_valid_31_mlxtranTask[] = {
0x10,0x0,0x20,0x0,0x20,0x0};
D_Reduction * d_reductions_32_mlxtranTask[] = {&d_reduction_10_mlxtranTask};
D_Reduction * d_reductions_33_mlxtranTask[] = {&d_reduction_5_mlxtranTask};
D_Reduction * d_reductions_34_mlxtranTask[] = {&d_reduction_17_mlxtranTask};
unsigned char d_goto_valid_35_mlxtranTask[] = {
0x40,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_35_mlxtranTask[] = {&d_reduction_8_mlxtranTask};
unsigned char d_goto_valid_36_mlxtranTask[] = {
0x80,0x0,0x0,0x30,0x0,0x0};
unsigned char d_goto_valid_37_mlxtranTask[] = {
0x10,0x0,0x20,0x0,0x20,0x0};
D_Reduction * d_reductions_38_mlxtranTask[] = {&d_reduction_6_mlxtranTask};
D_Reduction * d_reductions_39_mlxtranTask[] = {&d_reduction_7_mlxtranTask};
D_Reduction * d_reductions_40_mlxtranTask[] = {&d_reduction_9_mlxtranTask};
unsigned short d_gotos_mlxtranTask[70] = {
4,5,6,11,12,13,14,16,26,7,8,27,7,8,9,28,
17,9,19,20,10,37,21,10,0,22,23,31,33,36,15,24,
18,15,40,41,3,21,25,3,22,35,29,0,0,34,34,30,
0,0,0,32,34,25,3,38,39,0,0,0,0,3,3,0,
0,0,0,0,3,3};

D_ErrorRecoveryHint d_error_recovery_hints_0_mlxtranTask[] = {{0, 11, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_6_mlxtranTask[] = {{1, 11, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_13_mlxtranTask[] = {
{0, 5, "}"},
{2, 11, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_23_mlxtranTask[] = {{3, 11, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_24_mlxtranTask[] = {{1, 5, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_26_mlxtranTask[] = {{4, 11, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_27_mlxtranTask[] = {{2, 5, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_28_mlxtranTask[] = {{0, 5, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_29_mlxtranTask[] = {{5, 11, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_31_mlxtranTask[] = {{3, 5, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_35_mlxtranTask[] = {{4, 5, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_36_mlxtranTask[] = {{5, 5, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_38_mlxtranTask[] = {{6, 5, "}"}};

D_State d_states_mlxtranTask[] = {
{d_goto_valid_0_mlxtranTask, 1, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_0_mlxtranTask}, 1, NULL, (void*)d_scanner_0_mlxtranTask, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_mlxtranTask, d_accepts_diff_0_mlxtranTask, -1},
{d_goto_valid_1_mlxtranTask, 19, {1, d_reductions_1_mlxtranTask}, {1, d_right_epsilon_hints_1_mlxtranTask}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_2_mlxtranTask}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {0, NULL}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 1, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_4_mlxtranTask, -2, {1, d_reductions_4_mlxtranTask}, {0, NULL}, {1, d_error_recovery_hints_0_mlxtranTask}, 1, NULL, (void*)d_scanner_0_mlxtranTask, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_mlxtranTask, d_accepts_diff_0_mlxtranTask, -1},
{NULL, -2147483647, {1, d_reductions_5_mlxtranTask}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_6_mlxtranTask, 25, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_6_mlxtranTask}, 1, NULL, (void*)d_scanner_6_mlxtranTask, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_6_mlxtranTask, d_accepts_diff_6_mlxtranTask, -1},
{d_goto_valid_7_mlxtranTask, 9, {1, d_reductions_7_mlxtranTask}, {1, d_right_epsilon_hints_7_mlxtranTask}, {0, NULL}, 1, NULL, (void*)d_scanner_7_mlxtranTask, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_7_mlxtranTask, d_accepts_diff_7_mlxtranTask, -1},
{NULL, -2147483647, {1, d_reductions_8_mlxtranTask}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_9_mlxtranTask}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {0, NULL}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 1, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_11_mlxtranTask, 6, {1, d_reductions_11_mlxtranTask}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_11_mlxtranTask, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_11_mlxtranTask, d_accepts_diff_11_mlxtranTask, -1},
{NULL, -2147483647, {1, d_reductions_12_mlxtranTask}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_13_mlxtranTask, -17, {1, d_reductions_13_mlxtranTask}, {0, NULL}, {2, d_error_recovery_hints_13_mlxtranTask}, 1, NULL, (void*)d_scanner_0_mlxtranTask, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_mlxtranTask, d_accepts_diff_0_mlxtranTask, -1},
{d_goto_valid_14_mlxtranTask, 32, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_14_mlxtranTask, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_14_mlxtranTask, d_accepts_diff_14_mlxtranTask, -1},
{NULL, -2147483647, {1, d_reductions_15_mlxtranTask}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_16_mlxtranTask}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_17_mlxtranTask}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_18_mlxtranTask}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_19_mlxtranTask}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_20_mlxtranTask}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_21_mlxtranTask}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_22_mlxtranTask}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_23_mlxtranTask, 1, {1, d_reductions_23_mlxtranTask}, {0, NULL}, {1, d_error_recovery_hints_23_mlxtranTask}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_24_mlxtranTask, 11, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_24_mlxtranTask}, 1, NULL, (void*)d_scanner_24_mlxtranTask, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_24_mlxtranTask, d_accepts_diff_24_mlxtranTask, -1},
{NULL, -2147483647, {1, d_reductions_25_mlxtranTask}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_26_mlxtranTask, -14, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_26_mlxtranTask}, 1, NULL, (void*)d_scanner_26_mlxtranTask, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_26_mlxtranTask, d_accepts_diff_26_mlxtranTask, -1},
{d_goto_valid_27_mlxtranTask, -24, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_27_mlxtranTask}, 1, NULL, (void*)d_scanner_27_mlxtranTask, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_27_mlxtranTask, d_accepts_diff_27_mlxtranTask, -1},
{d_goto_valid_28_mlxtranTask, -32, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_28_mlxtranTask}, 1, NULL, (void*)d_scanner_0_mlxtranTask, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_mlxtranTask, d_accepts_diff_0_mlxtranTask, -1},
{NULL, -2147483647, {1, d_reductions_29_mlxtranTask}, {0, NULL}, {1, d_error_recovery_hints_29_mlxtranTask}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_30_mlxtranTask}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_31_mlxtranTask, -25, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_31_mlxtranTask}, 1, NULL, (void*)d_scanner_0_mlxtranTask, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_mlxtranTask, d_accepts_diff_0_mlxtranTask, -1},
{NULL, -2147483647, {1, d_reductions_32_mlxtranTask}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_33_mlxtranTask}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_34_mlxtranTask}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_35_mlxtranTask, -15, {1, d_reductions_35_mlxtranTask}, {0, NULL}, {1, d_error_recovery_hints_35_mlxtranTask}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_36_mlxtranTask, -27, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_36_mlxtranTask}, 1, NULL, (void*)d_scanner_36_mlxtranTask, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_36_mlxtranTask, d_accepts_diff_36_mlxtranTask, -1},
{d_goto_valid_37_mlxtranTask, -31, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_0_mlxtranTask, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_mlxtranTask, d_accepts_diff_0_mlxtranTask, -1},
{NULL, -2147483647, {1, d_reductions_38_mlxtranTask}, {0, NULL}, {1, d_error_recovery_hints_38_mlxtranTask}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_39_mlxtranTask}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_40_mlxtranTask}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1}
};

D_Symbol d_symbols_mlxtranTask[] = {
{D_SYMBOL_EBNF, "0 Start", 7, -1},
{D_SYMBOL_NTERM, "statement_list", 14, -1},
{D_SYMBOL_INTERNAL, "statement_list__3", 17, -1},
{D_SYMBOL_EBNF, "statement_list__2", 17, -1},
{D_SYMBOL_NTERM, "varOp", 5, -1},
{D_SYMBOL_NTERM, "funMultiOp", 10, -1},
{D_SYMBOL_INTERNAL, "funMultiOp__7", 13, -1},
{D_SYMBOL_EBNF, "funMultiOp__6", 13, -1},
{D_SYMBOL_NTERM, "funOp", 5, -1},
{D_SYMBOL_NTERM, "argOp", 5, -1},
{D_SYMBOL_NTERM, "funName", 7, -1},
{D_SYMBOL_NTERM, "functionLine", 12, -1},
{D_SYMBOL_INTERNAL, "functionLine__14", 16, -1},
{D_SYMBOL_EBNF, "functionLine__13", 16, -1},
{D_SYMBOL_INTERNAL, "functionLine__12", 16, -1},
{D_SYMBOL_NTERM, "statement", 9, -1},
{D_SYMBOL_INTERNAL, "statement__16", 13, -1},
{D_SYMBOL_NTERM, "constant", 8, -1},
{D_SYMBOL_NTERM, "decimalint", 10, -1},
{D_SYMBOL_NTERM, "float1", 6, -1},
{D_SYMBOL_NTERM, "float2", 6, -1},
{D_SYMBOL_NTERM, "identifier", 10, -1},
{D_SYMBOL_NTERM, "whitespace", 10, 1},
{D_SYMBOL_INTERNAL, "whitespace__24", 14, -1},
{D_SYMBOL_EBNF, "whitespace__23", 14, -1},
{D_SYMBOL_NTERM, "singleLineComment", 17, -1},
{D_SYMBOL_STRING, "=", 1, -1},
{D_SYMBOL_STRING, "{", 1, -1},
{D_SYMBOL_STRING, ",", 1, -1},
{D_SYMBOL_STRING, "}", 1, -1},
{D_SYMBOL_STRING, "=", 1, -1},
{D_SYMBOL_STRING, "(", 1, -1},
{D_SYMBOL_STRING, ",", 1, -1},
{D_SYMBOL_STRING, ")", 1, -1},
{D_SYMBOL_REGEX, "0|([1-9][0-9]*)", 15, -1},
{D_SYMBOL_REGEX, "([0-9]+.[0-9]*|[0-9]*.[0-9]+)([eE][\\\\-\\\\+]?[0-9]+)?", 55, -1},
{D_SYMBOL_REGEX, "[0-9]+[eE][\\\\-\\\\+]?[0-9]+", 29, -1},
{D_SYMBOL_REGEX, "[a-zA-Z][a-zA-Z0-9_]*", 21, -1},
{D_SYMBOL_REGEX, "[ \\t\\r\\n]+", 13, -1},
{D_SYMBOL_REGEX, "[;]", 3, -1},
{D_SYMBOL_REGEX, "[^\\n]*", 7, -1},
};

D_ParserTables parser_tables_mlxtranTask = {
41, d_states_mlxtranTask, d_gotos_mlxtranTask, 1, 41, d_symbols_mlxtranTask, NULL, 0, NULL, 0};
