#include <R.h>
#include <Rinternals.h>
#define printf Rprintf

/*
  Generated by Make DParser Version 1.31.4ab9d43046e5d22ffb365ec5f5184a7cfee09b30
  Available at https://github.com/jplevyak/dparser
*/

#line 7 "/home/matt/src/monolix2rx/src/summaryData.g.d_parser.c"
#include "dparse.h"

D_Reduction d_reduction_0_summaryData = {1, 0, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_1_summaryData = {1, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_2_summaryData = {2, 2, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_3_summaryData = {1, 2, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_4_summaryData = {1, 3, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_5_summaryData = {2, 4, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_8_summaryData = {1, 5, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_9_summaryData = {0, 5, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_10_summaryData = {1, 6, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_11_summaryData = {0, 6, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_12_summaryData = {1, 7, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_13_summaryData = {0, 7, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_14_summaryData = {5, 8, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_15_summaryData = {8, 9, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_16_summaryData = {5, 10, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_17_summaryData = {1, 11, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_18_summaryData = {1, 12, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_19_summaryData = {1, 13, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_20_summaryData = {1, 14, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_21_summaryData = {1, 15, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_22_summaryData = {2, 16, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_23_summaryData = {0, 16, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_24_summaryData = {1, 17, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_26_summaryData = {2, 18, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_0_summaryData = {19, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_1_summaryData = {20, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_2_summaryData = {21, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_3_summaryData = {22, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_4_summaryData = {23, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_5_summaryData = {24, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_6_summaryData = {25, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_7_summaryData = {26, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_8_summaryData = {27, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_9_summaryData = {28, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_10_summaryData = {29, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_11_summaryData = {30, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_12_summaryData = {31, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_13_summaryData = {32, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_14_summaryData = {33, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_15_summaryData = {34, 0, 0, 0, -1, 0, NULL};
D_Shift d_shift_16_summaryData = {35, 0, 0, 0, -2, 0, NULL};
D_Shift d_shift_17_summaryData = {36, 0, 0, 0, -3, 0, NULL};
D_Shift d_shift_18_summaryData = {37, 0, 0, 0, -4, 0, NULL};
D_Shift d_shift_19_summaryData = {38, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_20_summaryData = {39, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_21_summaryData = {40, 0, 0, 0, 0, 0, NULL};

D_Shift * d_accepts_diff_0_0_summaryData[] = {0};
D_Shift ** d_accepts_diff_0_summaryData[] = {
d_accepts_diff_0_0_summaryData
};

unsigned char d_scanner_0_0_0_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_0_0_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_0_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_1_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_2_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_3_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_4_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_5_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_6_summaryData[] = {&d_shift_0_summaryData,NULL};

D_Shift * d_accepts_diff_2_0_summaryData[] = {0};
D_Shift ** d_accepts_diff_2_summaryData[] = {
d_accepts_diff_2_0_summaryData
};

unsigned char d_scanner_2_0_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_2_1_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_2_2_summaryData[] = {&d_shift_1_summaryData,NULL};

D_Shift * d_accepts_diff_7_0_summaryData[] = {0};
D_Shift ** d_accepts_diff_7_summaryData[] = {
d_accepts_diff_7_0_summaryData
};

unsigned char d_scanner_7_0_0_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 
};

D_Shift * d_shift_7_1_summaryData[] = {&d_shift_20_summaryData,NULL};

D_Shift * d_accepts_diff_11_0_summaryData[] = {0};
D_Shift ** d_accepts_diff_11_summaryData[] = {
d_accepts_diff_11_0_summaryData
};

unsigned char d_scanner_11_0_0_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 
};

unsigned char d_scanner_11_1_0_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_11_1_summaryData[] = {&d_shift_19_summaryData,NULL};

D_Shift * d_accepts_diff_12_0_summaryData[] = {0};
D_Shift ** d_accepts_diff_12_summaryData[] = {
d_accepts_diff_12_0_summaryData
};

unsigned char d_scanner_12_0_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 4, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_1_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_2_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_3_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_4_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_5_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_6_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_7_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_8_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_9_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_10_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_11_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_12_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_12_13_summaryData[] = {&d_shift_13_summaryData,NULL};

unsigned char d_scanner_12_14_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_15_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_16_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 19, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_17_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_18_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_19_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_20_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 23, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_21_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_22_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 25, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_23_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_24_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_25_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_12_26_summaryData[] = {&d_shift_2_summaryData,NULL};

unsigned char d_scanner_12_27_1_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 29, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_12_28_summaryData[] = {&d_shift_6_summaryData,NULL};

D_Shift * d_accepts_diff_14_0_summaryData[] = {0};
D_Shift ** d_accepts_diff_14_summaryData[] = {
d_accepts_diff_14_0_summaryData
};

unsigned char d_scanner_14_0_0_summaryData[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

unsigned char d_scanner_14_0_1_summaryData[SCANNER_BLOCK_SIZE] = {
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

D_Shift * d_shift_14_0_summaryData[] = {&d_shift_21_summaryData,NULL};

D_Shift * d_accepts_diff_24_0_summaryData[] = {0};
D_Shift ** d_accepts_diff_24_summaryData[] = {
d_accepts_diff_24_0_summaryData
};

unsigned char d_scanner_24_0_0_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_24_1_summaryData[] = {&d_shift_3_summaryData,NULL};

D_Shift * d_accepts_diff_25_0_summaryData[] = {0};
D_Shift ** d_accepts_diff_25_summaryData[] = {
d_accepts_diff_25_0_summaryData
};

unsigned char d_scanner_25_0_0_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_25_1_summaryData[] = {&d_shift_7_summaryData,NULL};

D_Shift * d_accepts_diff_28_0_summaryData[] = {0};
D_Shift ** d_accepts_diff_28_summaryData[] = {
d_accepts_diff_28_0_summaryData
};

unsigned char d_scanner_28_0_0_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_28_1_summaryData[] = {&d_shift_15_summaryData,NULL};

unsigned char d_scanner_28_2_0_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_accepts_diff_29_0_summaryData[] = {0};
D_Shift ** d_accepts_diff_29_summaryData[] = {
d_accepts_diff_29_0_summaryData
};

unsigned char d_scanner_29_0_0_summaryData[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

D_Shift * d_shift_29_0_summaryData[] = {&d_shift_8_summaryData,NULL};

D_Shift * d_accepts_diff_33_0_summaryData[] = {0};
D_Shift ** d_accepts_diff_33_summaryData[] = {
d_accepts_diff_33_0_summaryData
};

unsigned char d_scanner_33_0_0_summaryData[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_33_1_summaryData[] = {&d_shift_9_summaryData,NULL};

SB_uint8 d_scanner_0_summaryData[7] = {
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_0_0_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_0_1_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_0_2_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_0_3_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_0_4_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_0_5_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{d_shift_0_6_summaryData, {d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}}
};

SB_trans_uint8 d_transition_0_summaryData[7] = {
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}}
};

SB_uint8 d_scanner_2_summaryData[3] = {
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_2_0_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_2_1_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{d_shift_2_2_summaryData, {d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}}
};

SB_trans_uint8 d_transition_2_summaryData[3] = {
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}}
};

SB_uint8 d_scanner_7_summaryData[2] = {
{NULL, {d_scanner_7_0_0_summaryData, d_scanner_0_0_0_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{d_shift_7_1_summaryData, {d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}}
};

SB_trans_uint8 d_transition_7_summaryData[2] = {
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}}
};

SB_uint8 d_scanner_11_summaryData[3] = {
{NULL, {d_scanner_11_0_0_summaryData, d_scanner_0_0_0_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{d_shift_11_1_summaryData, {d_scanner_11_1_0_summaryData, d_scanner_0_0_0_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{d_shift_7_1_summaryData, {d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}}
};

SB_trans_uint8 d_transition_11_summaryData[3] = {
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}}
};

SB_uint8 d_scanner_12_summaryData[29] = {
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_0_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_1_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_2_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_3_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_4_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_5_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_6_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_7_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_8_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_9_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_10_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_11_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_12_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{d_shift_12_13_summaryData, {d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_14_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_15_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_16_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_17_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_18_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_19_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_20_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_21_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_22_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_23_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_24_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_25_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{d_shift_12_26_summaryData, {d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{NULL, {d_scanner_0_0_0_summaryData, d_scanner_12_27_1_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{d_shift_12_28_summaryData, {d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}}
};

SB_trans_uint8 d_transition_12_summaryData[29] = {
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}}
};

SB_uint8 d_scanner_14_summaryData[2] = {
{d_shift_14_0_summaryData, {d_scanner_14_0_0_summaryData, d_scanner_14_0_1_summaryData
 , d_scanner_14_0_1_summaryData, d_scanner_14_0_1_summaryData}},
{d_shift_14_0_summaryData, {d_scanner_14_0_0_summaryData, d_scanner_14_0_1_summaryData
 , d_scanner_14_0_1_summaryData, d_scanner_14_0_1_summaryData}}
};

SB_trans_uint8 d_transition_14_summaryData[2] = {
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}}
};

SB_uint8 d_scanner_24_summaryData[2] = {
{NULL, {d_scanner_24_0_0_summaryData, d_scanner_0_0_0_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{d_shift_24_1_summaryData, {d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}}
};

SB_trans_uint8 d_transition_24_summaryData[2] = {
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}}
};

SB_uint8 d_scanner_25_summaryData[2] = {
{NULL, {d_scanner_25_0_0_summaryData, d_scanner_0_0_0_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{d_shift_25_1_summaryData, {d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}}
};

SB_trans_uint8 d_transition_25_summaryData[2] = {
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}}
};

SB_uint8 d_scanner_28_summaryData[3] = {
{NULL, {d_scanner_28_0_0_summaryData, d_scanner_0_0_0_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{d_shift_28_1_summaryData, {d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{d_shift_28_1_summaryData, {d_scanner_28_2_0_summaryData, d_scanner_0_0_0_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}}
};

SB_trans_uint8 d_transition_28_summaryData[3] = {
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}}
};

SB_uint8 d_scanner_29_summaryData[2] = {
{d_shift_29_0_summaryData, {d_scanner_29_0_0_summaryData, d_scanner_14_0_1_summaryData
 , d_scanner_14_0_1_summaryData, d_scanner_14_0_1_summaryData}},
{d_shift_29_0_summaryData, {d_scanner_29_0_0_summaryData, d_scanner_14_0_1_summaryData
 , d_scanner_14_0_1_summaryData, d_scanner_14_0_1_summaryData}}
};

SB_trans_uint8 d_transition_29_summaryData[2] = {
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}}
};

SB_uint8 d_scanner_33_summaryData[2] = {
{NULL, {d_scanner_33_0_0_summaryData, d_scanner_0_0_0_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}},
{d_shift_33_1_summaryData, {d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData
 , d_scanner_0_0_0_summaryData, d_scanner_0_0_0_summaryData}}
};

SB_trans_uint8 d_transition_33_summaryData[2] = {
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}},
{{d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData
 , d_accepts_diff_0_0_0_summaryData, d_accepts_diff_0_0_0_summaryData}}
};

unsigned char d_goto_valid_0_summaryData[] = {
0x1e,0x7,0x8,0x0,0x0,0x0};
unsigned char d_goto_valid_1_summaryData[] = {
0x0,0x80,0x1,0x0,0x0,0x0};
D_Reduction * d_reductions_1_summaryData[] = {&d_reduction_23_summaryData};
D_RightEpsilonHint d_right_epsilon_hints_1_summaryData[] = {{0, 11, &d_reduction_21_summaryData}};
unsigned char d_goto_valid_2_summaryData[] = {
0x0,0x0,0x10,0x0,0x0,0x0};
unsigned char d_goto_valid_4_summaryData[] = {
0x18,0x7,0x8,0x0,0x0,0x0};
D_Reduction * d_reductions_4_summaryData[] = {&d_reduction_1_summaryData};
D_Reduction * d_reductions_5_summaryData[] = {&d_reduction_3_summaryData};
D_Reduction * d_reductions_6_summaryData[] = {&d_reduction_4_summaryData};
unsigned char d_goto_valid_7_summaryData[] = {
0x80,0x0,0x4,0x0,0x80,0x0};
D_Reduction * d_reductions_7_summaryData[] = {&d_reduction_13_summaryData};
D_RightEpsilonHint d_right_epsilon_hints_7_summaryData[] = {{0, 15, &d_reduction_5_summaryData}};
unsigned char d_goto_valid_8_summaryData[] = {
0x40,0x0,0x4,0x0,0x80,0x0};
D_Reduction * d_reductions_8_summaryData[] = {&d_reduction_11_summaryData};
D_RightEpsilonHint d_right_epsilon_hints_8_summaryData[] = {{0, 17, &d_reduction_5_summaryData}};
unsigned char d_goto_valid_9_summaryData[] = {
0x20,0x0,0x4,0x0,0x80,0x0};
D_Reduction * d_reductions_9_summaryData[] = {&d_reduction_9_summaryData};
D_RightEpsilonHint d_right_epsilon_hints_9_summaryData[] = {{0, 19, &d_reduction_5_summaryData}};
unsigned char d_goto_valid_11_summaryData[] = {
0x0,0x0,0x6,0x0,0xc0,0x0};
D_Reduction * d_reductions_11_summaryData[] = {&d_reduction_21_summaryData};
unsigned char d_goto_valid_12_summaryData[] = {
0x0,0x0,0x20,0x2,0x1,0x0};
D_Reduction * d_reductions_13_summaryData[] = {&d_reduction_2_summaryData};
unsigned char d_goto_valid_14_summaryData[] = {
0x0,0x0,0x0,0x0,0x0,0x1};
D_Reduction * d_reductions_15_summaryData[] = {&d_reduction_5_summaryData};
D_Reduction * d_reductions_16_summaryData[] = {&d_reduction_12_summaryData};
D_Reduction * d_reductions_17_summaryData[] = {&d_reduction_5_summaryData};
D_Reduction * d_reductions_18_summaryData[] = {&d_reduction_10_summaryData};
D_Reduction * d_reductions_19_summaryData[] = {&d_reduction_5_summaryData};
D_Reduction * d_reductions_20_summaryData[] = {&d_reduction_8_summaryData};
D_Reduction * d_reductions_21_summaryData[] = {&d_reduction_24_summaryData};
D_Reduction * d_reductions_22_summaryData[] = {&d_reduction_22_summaryData};
D_Reduction * d_reductions_23_summaryData[] = {&d_reduction_24_summaryData};
unsigned char d_goto_valid_24_summaryData[] = {
0x0,0x0,0x40,0x0,0x0,0x0};
unsigned char d_goto_valid_25_summaryData[] = {
0x0,0x0,0x0,0x4,0x0,0x0};
unsigned char d_goto_valid_26_summaryData[] = {
0x0,0x0,0x40,0x0,0x0,0x0};
D_Reduction * d_reductions_27_summaryData[] = {&d_reduction_26_summaryData};
unsigned char d_goto_valid_28_summaryData[] = {
0x0,0x8,0x0,0x0,0x4,0x0};
unsigned char d_goto_valid_29_summaryData[] = {
0x0,0x0,0x0,0x8,0x0,0x0};
unsigned char d_goto_valid_30_summaryData[] = {
0x0,0x8,0x0,0x0,0x4,0x0};
D_Reduction * d_reductions_31_summaryData[] = {&d_reduction_17_summaryData};
D_Reduction * d_reductions_32_summaryData[] = {&d_reduction_14_summaryData};
unsigned char d_goto_valid_33_summaryData[] = {
0x0,0x0,0x0,0x10,0x0,0x0};
D_Reduction * d_reductions_34_summaryData[] = {&d_reduction_16_summaryData};
unsigned char d_goto_valid_35_summaryData[] = {
0x0,0x0,0x40,0x0,0x0,0x0};
unsigned char d_goto_valid_36_summaryData[] = {
0x0,0x8,0x0,0x0,0x4,0x0};
D_Reduction * d_reductions_37_summaryData[] = {&d_reduction_15_summaryData};
unsigned short d_gotos_summaryData[61] = {
4,5,6,7,11,12,13,8,9,10,14,7,16,18,20,8,
9,10,3,23,24,28,29,17,25,19,3,21,26,30,31,33,
34,35,36,27,37,38,0,0,22,15,0,0,15,0,15,0,
15,0,0,0,0,0,32,0,32,0,0,0,32};


D_State d_states_summaryData[] = {
{d_goto_valid_0_summaryData, 1, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_0_summaryData, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_summaryData, d_accepts_diff_0_summaryData, -1},
{d_goto_valid_1_summaryData, 11, {1, d_reductions_1_summaryData}, {1, d_right_epsilon_hints_1_summaryData}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_2_summaryData, 14, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_2_summaryData, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_2_summaryData, d_accepts_diff_2_summaryData, -1},
{NULL, -2147483647, {0, NULL}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 1, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_4_summaryData, -7, {1, d_reductions_4_summaryData}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_0_summaryData, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_summaryData, d_accepts_diff_0_summaryData, -1},
{NULL, -2147483647, {1, d_reductions_5_summaryData}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_6_summaryData}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_7_summaryData, -5, {1, d_reductions_7_summaryData}, {1, d_right_epsilon_hints_7_summaryData}, {0, NULL}, 1, NULL, (void*)d_scanner_7_summaryData, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_7_summaryData, d_accepts_diff_7_summaryData, -1},
{d_goto_valid_8_summaryData, -7, {1, d_reductions_8_summaryData}, {1, d_right_epsilon_hints_8_summaryData}, {0, NULL}, 1, NULL, (void*)d_scanner_7_summaryData, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_7_summaryData, d_accepts_diff_7_summaryData, -1},
{d_goto_valid_9_summaryData, -9, {1, d_reductions_9_summaryData}, {1, d_right_epsilon_hints_9_summaryData}, {0, NULL}, 1, NULL, (void*)d_scanner_7_summaryData, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_7_summaryData, d_accepts_diff_7_summaryData, -1},
{NULL, -2147483647, {0, NULL}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 1, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_11_summaryData, -2, {1, d_reductions_11_summaryData}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_11_summaryData, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_11_summaryData, d_accepts_diff_11_summaryData, -1},
{d_goto_valid_12_summaryData, -3, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_12_summaryData, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_12_summaryData, d_accepts_diff_12_summaryData, -1},
{NULL, -2147483647, {1, d_reductions_13_summaryData}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_14_summaryData, 19, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_14_summaryData, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_14_summaryData, d_accepts_diff_14_summaryData, -1},
{NULL, -2147483647, {1, d_reductions_15_summaryData}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_16_summaryData}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_17_summaryData}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_18_summaryData}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_19_summaryData}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_20_summaryData}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_21_summaryData}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_22_summaryData}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_23_summaryData}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_24_summaryData, 0, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_24_summaryData, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_24_summaryData, d_accepts_diff_24_summaryData, -1},
{d_goto_valid_25_summaryData, -3, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_25_summaryData, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_25_summaryData, d_accepts_diff_25_summaryData, -1},
{d_goto_valid_26_summaryData, -8, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_24_summaryData, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_24_summaryData, d_accepts_diff_24_summaryData, -1},
{NULL, -2147483647, {1, d_reductions_27_summaryData}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_28_summaryData, -20, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_28_summaryData, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_28_summaryData, d_accepts_diff_28_summaryData, -1},
{d_goto_valid_29_summaryData, -5, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_29_summaryData, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_29_summaryData, d_accepts_diff_29_summaryData, -1},
{d_goto_valid_30_summaryData, -22, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_28_summaryData, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_28_summaryData, d_accepts_diff_28_summaryData, -1},
{NULL, -2147483647, {1, d_reductions_31_summaryData}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_32_summaryData}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_33_summaryData, -6, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_33_summaryData, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_33_summaryData, d_accepts_diff_33_summaryData, -1},
{NULL, -2147483647, {1, d_reductions_34_summaryData}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_35_summaryData, -14, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_24_summaryData, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_24_summaryData, d_accepts_diff_24_summaryData, -1},
{d_goto_valid_36_summaryData, -26, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_28_summaryData, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_28_summaryData, d_accepts_diff_28_summaryData, -1},
{NULL, -2147483647, {1, d_reductions_37_summaryData}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1}
};

D_Symbol d_symbols_summaryData[] = {
{D_SYMBOL_EBNF, "0 Start", 7, -1},
{D_SYMBOL_NTERM, "statement_list", 14, -1},
{D_SYMBOL_INTERNAL, "statement_list__3", 17, -1},
{D_SYMBOL_EBNF, "statement_list__2", 17, -1},
{D_SYMBOL_NTERM, "statement", 9, -1},
{D_SYMBOL_INTERNAL, "statement__7", 12, -1},
{D_SYMBOL_INTERNAL, "statement__6", 12, -1},
{D_SYMBOL_INTERNAL, "statement__5", 12, -1},
{D_SYMBOL_NTERM, "nind", 4, -1},
{D_SYMBOL_NTERM, "nobs", 4, -1},
{D_SYMBOL_NTERM, "ndose", 5, -1},
{D_SYMBOL_NTERM, "decimalint", 10, -1},
{D_SYMBOL_NTERM, "float1", 6, -1},
{D_SYMBOL_NTERM, "float2", 6, -1},
{D_SYMBOL_NTERM, "identifier", 10, -1},
{D_SYMBOL_NTERM, "whitespace", 10, 1},
{D_SYMBOL_INTERNAL, "whitespace__17", 14, -1},
{D_SYMBOL_EBNF, "whitespace__16", 14, -1},
{D_SYMBOL_NTERM, "singleLineComment", 17, -1},
{D_SYMBOL_STRING, "Number", 6, -1},
{D_SYMBOL_STRING, "of", 2, -1},
{D_SYMBOL_STRING, "individuals", 11, -1},
{D_SYMBOL_STRING, ":", 1, -1},
{D_SYMBOL_STRING, "Number", 6, -1},
{D_SYMBOL_STRING, "of", 2, -1},
{D_SYMBOL_STRING, "observations", 12, -1},
{D_SYMBOL_STRING, "(", 1, -1},
{D_SYMBOL_REGEX, "[^)]*", 5, -1},
{D_SYMBOL_STRING, ")", 1, -1},
{D_SYMBOL_STRING, ":", 1, -1},
{D_SYMBOL_STRING, "Number", 6, -1},
{D_SYMBOL_STRING, "of", 2, -1},
{D_SYMBOL_STRING, "doses", 5, -1},
{D_SYMBOL_STRING, ":", 1, -1},
{D_SYMBOL_REGEX, "0|([1-9][0-9]*)", 15, -1},
{D_SYMBOL_REGEX, "([0-9]+.[0-9]*|[0-9]*.[0-9]+)([eE][\\\\-\\\\+]?[0-9]+)?", 55, -1},
{D_SYMBOL_REGEX, "[0-9]+[eE][\\\\-\\\\+]?[0-9]+", 29, -1},
{D_SYMBOL_REGEX, "[a-zA-Z][a-zA-Z0-9_]*", 21, -1},
{D_SYMBOL_REGEX, "[ \\t\\r\\n]+", 13, -1},
{D_SYMBOL_REGEX, "[;]", 3, -1},
{D_SYMBOL_REGEX, "[^\\n]*", 7, -1},
};

D_ParserTables parser_tables_summaryData = {
38, d_states_summaryData, d_gotos_summaryData, 1, 41, d_symbols_summaryData, NULL, 0, NULL, 0};
