SEXP monolix2rxAddVar(const char *var);
SEXP monolix2rxSetDist(const char *var);
SEXP _monolix2rx_trans_longEq(SEXP in);
SEXP _monolix2rx_trans_indDef(SEXP in);
SEXP monolix2rxSetDistTypicalEst(const char *var, int isMean);
SEXP monolix2rxSetDistTypicalFixed(const char *var, int isMean);
SEXP monolix2rxSetSd(const char *var);
SEXP monolix2rxSetVar(const char *var);
SEXP monolix2rxSetMax(const char *var);
SEXP monolix2rxSetMin(const char *var);
SEXP monolix2rxSetIov(const char *var);
SEXP monolix2rxAddCov(const char *var);
SEXP monolix2rxPushCoefList(void);
SEXP monolix2rxAddCoefSingle(const char *var);
SEXP monolix2rxAddCoefMult(const char *var);
SEXP monolix2rxAddCor(const char *v1, const char *v2, const char *v3);
SEXP monolix2rxSetCorLevel(const char *v);
void nonmem2rx_full_ini(void);
